### PR TITLE
update glm signatures to accept SoA matrices

### PR DESCRIPTION
**Pull request by SteveBronder**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Turns on SoA matrices for glm lpdf functions

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by andrjohns** [comment]
Great to see this coming in! Is there a way of testing that SoA support successfully compiles, or is that implicitly tested once it's enabled?

**Comment by WardBrian** [comment]
This relies on the already-merged https://github.com/stan-dev/math/pull/2655, right?

**Comment by SteveBronder** [comment]
> Great to see this coming in! Is there a way of testing that SoA support successfully compiles, or is that implicitly tested once it's enabled?

So once we do the next version we are going to bump `O1` to be the default which means SoA will be tested everywhere. But for now I just tested this locally and the tests in Stanc3 that use the glm signatures compile locally for me

> This relies on the already-merged stan-dev/math#2655, right?

Yep!

**Review by WardBrian — APPROVED** [review]
LGTM

**Pull request merged**
