### PR TITLE
Expose fft and inv_fft

### PR DESCRIPTION
**Pull request by WardBrian**
Relies on https://github.com/stan-dev/math/pull/2686/

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [x] If a user-facing facing change was made, the documentation PR is here: https://github.com/stan-dev/docs/pull/524/
   
## Release notes

Added `fft`, `inv_fft`, `fft2`, and `inv_fft2` to the language.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Looks good!

**Comment by WardBrian** [comment]
Yes, I just set the math branch for the first round of tests to confirm it all passes. We will also need doc for these.

**Comment by WardBrian** [comment]
@bob-carpenter I've started really bare-bones doc for this here - https://github.com/stan-dev/docs/tree/fft-doc

It basically just adds the signatures and a throw away line about what the function does. Would you mind going in and adding some LaTeX about the definition of the FFT and how our implementation works (e.g., I believe we perform the re-scaling necessary so that `inv_fft(fft(x)) == x`, which not all implementations do)

**Comment by bob-carpenter** [comment]
> Would you mind going in and adding some LaTeX about the definition of the FFT and how our implementation works 

Will do.

**Pull request merged**
