### PR TITLE
Add require_* templates to generated functions

### LINKED ISSUE #1105: [BUG] Function overloading when the number of arguments match is a bit brittle
Example of a model that fails to compile:

```stan
functions {
   real foo(row_vector p) {
   	return sum(p) + 1;
   }
   real foo(vector p) {
   	return sum(p) + 1;
   }
}
transformed data{
   vector[5] a = [0.1, 0.1, 0.1, 0.1, 0.1]';
}
parameters {
    real y;
}
model {
    y ~ normal(foo(a), 1);
}
```
In this example model, both functions are generated as the exact same code. See https://bit.ly/3rgYpcY 

The issue is that the UDF arguments are fully templated. The only exceptions are integers and when arrays are involved, then the type is `std::vector<T>`.

Changing the functions to the following fixes that the model compile: 
```stan
functions {
   real foo(row_vector p, real a) {
   	return sum(p) + 1;
   }
   real foo(vector p) {
   	return sum(p) + 1;
   }
}
```

What we need is to use the require template metaprograms. Not fun...

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Closes #1105 by adding `require_*` templates to the code generated by user-defined functions.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Looks good to me. Merge assuming tests pass. If @SteveBronder has time to have a look in the next day or two, I wouldn't mind him taking a quick peek at this for a sanity check. 

I think an RC2 is in line with this as well.

Thanks for jumping on this so quick!

**Comment by WardBrian** [comment]
@SteveBronder messaged me to say he can take a look later, which I'd also appreciate (never can be too careful around these templates)

**Review by SteveBronder — APPROVED** [review]
Looks good! There's a few cleanups I'd like to do in the codegen but nothing that's a blocker so those can wait till after the release

**Comment by rok-cesnovar** [comment]
One thing that I thought of now. What about if some args are varmat? Or do we not handle varmats with udfs?

**Comment by SteveBronder** [comment]
^not supported yet so all good

**Pull request merged**
