### PR TITLE
Add ode_ckrk and ode_ckrk_tol

### LINKED ISSUE #826: Expose ode_ckrk & ode_ckrk_tol
New variadic ode functions were added in https://github.com/stan-dev/math/pull/2336 and the docs pull is also open https://github.com/stan-dev/docs/pull/334

Additional ode functions can be added by adding them to the list: https://github.com/stan-dev/stanc3/blob/master/src/middle/Stan_math_signatures.ml#L165

Apart from that we only need a few test models: https://github.com/stan-dev/stanc3/tree/master/test/integration/good/ode

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Fixes #826 

## Release notes

Added ode_ckrk and ode_ckrk_tol to the Stan language.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Waiting on some test models to compile I figured I would close this simple one. Test models compile with develop math.

@bbbales2 Mind reviewing this?

@yizhang-yiz if you want to add any additional test models feel free to push here or paste them.

**Comment by yizhang-yiz** [comment]
oops, I'm about to submit a PR for this. I can review it.

**Review by yizhang-yiz — APPROVED** [review]

**Comment by rok-cesnovar** [comment]
Ah sorry, should have tagged you in the issue. Thanks for reviewing!

**Comment by yizhang-yiz** [comment]
No worries. Glad it's done.

**Comment by bbbales2** [comment]
There's a draft, at least: https://github.com/stan-dev/docs/pull/334/files . We added some stuff to the first ODE page to try to make it easier to pick between the different solvers.

Functions reference just got added today -- haven't reviewed it yet but something is there.

**Comment by wds15** [comment]
+1

**Pull request merged**
