### PR TITLE
[WIP] Multiarch stanc3 building

### PR DESCRIPTION
**Pull request by andrjohns**
## Release notes

Draft PR for testing multiarch stanc3 building via docker and qemu

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by andrjohns** [comment]
@serban-nicusor-toptal sorry to bother but it looks like one of the Jenkins machines doesn't have multiarch docker enabled. The host in the most recent Jenkins run throws an exec format error, would you be able to check the multiarch status when you've got a minute? Thanks!

**Comment by andrjohns** [comment]
@serban-nicusor-toptal Looks like the git set-up for Jenkins is struggling a little, would you mind having a look? Thanks!

**Comment by serban-nicusor-toptal** [comment]
I think this is because there's a mismatch in the Docker user ID and the Jenkins user ID we pass.
Is the Dockerfile for `andrjohns/stanc3-building:armhf-debootstrap` available somewhere so I can take a look at it ? Thanks

**Comment by andrjohns** [comment]
Ack didn't even think of that sorry. I'll copy across the addgroup setups for `jenkins-slave`, sorry for the wasted time!

**Comment by serban-nicusor-toptal** [comment]
No worries! Let me know if that works else we can take another look.

**Comment by andrjohns** [comment]
@serban-nicusor-toptal Still no luck unfortunately! Here's the [script I'm using to generate and build the docker image](https://github.com/stan-dev/stanc3/blob/3f4d621e55501c98cf07d593937bf9d6dab996e1/docker/multiarch/build_multiarch_docker.sh), anything obvious I'm missing?

**Comment by andrjohns** [comment]
For some strange reason this PR refuses to build anymore, so a new draft PR has been created

**Pull request closed without merging**
