### PR TITLE
Expose beta_neg_binomial_lpmf

### PR DESCRIPTION
**Pull request by WardBrian**
From https://github.com/stan-dev/math/pull/3108 (ping @lingium)

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    
## Release notes

Exposed new distribution `beta_neg_binomial`

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
@SteveBronder I couldn't tell if these signatures supported SoA or not -- do they?

**Comment by WardBrian** [comment]
@serban-nicusor-toptal this is getting an odd error in the expression tests, can you take a look? It looks like something isn't being deleted properly between runs

**Comment by SteveBronder** [comment]
Yes how it's written it should

**Comment by WardBrian** [comment]
This is now passing, mind approving @SteveBronder?


@lingium The next step is documenting the distribution for users at https://github.com/stan-dev/docs/tree/master/src/functions-reference -- would you mind giving that a go?

**Comment by lingium** [comment]
@WardBrian Sure, I can take care of that

**Pull request merged**
