### PR TITLE
Point Jenkins back to main docker images

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests

## Release notes

Following #1019, we have Jenkins using images like `stanorg/stanc3:static-ocaml-update`. @serban-nicusor-toptal is going to rename those back to the standard names (without `-ocaml-update`) now that it is merged, and this will go along with that.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This might just be noise and you are aware of it, so forgive me if that is the case, the master run failed: https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/master/966/pipeline

**Comment by WardBrian** [comment]
Yeah, luckily it failed at the internal documentation stage (e.g, nothing really bad). @serban-nicusor-toptal is on it, it is a permissions issue with that last step.

**Comment by serban-nicusor-toptal** [comment]
Hey, above issue should be fixed now. When we've switched to 4.12 docker image, it comes pre-bundled with the opam groups we were creating and for some reason it didn't like UID/GID 1000 because on our VM that isn't opam.

**Review by serban-nicusor-toptal — APPROVED** [review]
LGTM

**Pull request merged**
