### PR TITLE
ensure write_array writes all parameters even if there's an exception

### PR DESCRIPTION
**Pull request by nhuurre**
Fix stan-dev/stan#3114.
I'm pretty sure constraints on generated quantities never had any effect other than suppressing output so with this they're even more useless.

#### Submission Checklist

- [X] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

(are bugfixes "user-facing"?)

## Release notes

Exceptions in the generated quantities no longer hide all generated quantities; the ones assigned before the exception are now available in the output.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by fergusjchadwick** [comment]
Thanks for jumping on this @nhuurre. Not sure whether to add this to the issue or here (this is my first issue submission!).

> I'm pretty sure constraints on generated quantities never had any effect other than suppressing output so with this they're even more useless.

I do find them useful in generated quantities (or how I imagine they work/could work), for example, making sure something is a simplex following transformation is very handy.

**Comment by bob-carpenter** [comment]
@nhuurre :  I just saw the issue and feel very strongly that this should *not* be implemented for reasons I describe on the issue:  https://github.com/stan-dev/stan/issues/3114#issuecomment-1087640525

I am not sure about our process at this point.  I would like to close this so it's never merged.  But then you can get a vote of devs to overrule me.  I'm going to add a blocking review right now.

**Comment by nhuurre** [comment]
This PR now depends on stan-dev/stan#3116 and with that, the behavior is as Rok described on the issue https://github.com/stan-dev/stan/issues/3114#issuecomment-1087655016

**Comment by SteveBronder** [comment]
@bob-carpenter @nhuurre how do you feel about the alt approach in #1165? If any part of write_array fails then we just return NaN values for everything that is not a parameter

**Comment by bob-carpenter** [comment]
> If any part of write_array fails then we just return NaN values for everything that is not a parameter

This is my preference.

**Comment by WardBrian** [comment]
We decided to go with #1165 so I'm going to close this

**Pull request closed without merging**
