### PR TITLE
Add quantile signatures

### PR DESCRIPTION
**Pull request by adamhaber**
## Release notes

Adds signatures for data-only quantile functions.

Corresponding docs PR - https://github.com/stan-dev/docs/pull/350
Corresponding math PR - https://github.com/stan-dev/math/pull/2398

@rok-cesnovar - any idea why I don't get `data` annotations in `stan_math_sigs.expected`? I've tried to follow  other `DataOnly` signatures but I'm clearly missing something... I tried to follow @bbbales2 signatures here: https://github.com/stan-dev/math/pull/2398#pullrequestreview-627558208

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)
Adam Haber

### CODE REVIEW

**Comment by nhuurre** [comment]
> any idea why I don't get data annotations in stan_math_sigs.expected?

It's because `print_all_math_sigs` discards the autodiff type here
https://github.com/stan-dev/stanc3/blob/282439ea73cd348b22b09be78bb78875b03a0e64/src/middle/Stan_math_signatures.ml#L387-L388
That `snd` takes the second item in the tuple and ignores the first.
It should probably be
```ocaml
      (list ~sep:comma UnsizedType.pp_fun_arg)
      args UnsizedType.pp_returntype rt
```

**Comment by adamhaber** [comment]
AFAIU, Jenkins fails because the models https://github.com/stan-dev/example-models/tree/master/education/causal_rct have a quantile user-defined function, which is now a name clash. Should I open a separate PR there?

**Comment by rok-cesnovar** [comment]
Yeah, we need to replace the name in those 4 models.

**Review by rok-cesnovar — CHANGES_REQUESTED** [review]
The changes look good, only the test models are missing. 

Something like https://github.com/stan-dev/stanc3/blob/master/test/integration/good/function-signatures/math/functions/asinh.stan

**Review by rok-cesnovar — APPROVED** [review]
Looks good. Thanks!

Merge once tests pass, which wont be until the Math PR is merged and that gets propagated up to CmdStan.

**Comment by rok-cesnovar** [comment]
FTR: The required docs PR is also open: https://github.com/stan-dev/docs/pull/350

**Comment by SteveBronder** [comment]
Quantile math PR merged!

**Pull request merged**
