### PR TITLE
minor doc fix

### PR DESCRIPTION
**Pull request by ode33**

### CODE REVIEW

**Comment by VMatthijs** [comment]
@seantalts , any idea what the problem is with these performance tests?

**Comment by ode33** [comment]
Is there something amiss?

**Comment by seantalts** [comment]
You mean the end to end tests? It looks like opam removed old versions of Dune and Fmt today! I didn't realize they did that. We need to figure out how to pin versions...

**Comment by seantalts** [comment]
Hmm, opam looks like it has records of that version - maybe the Docker image just needs to run opam update first.

**Comment by seantalts** [comment]
@ode33 nothing you need to worry about - one of the Dockerfiles we use for testing is broken right now.

**Pull request merged**
