### PR TITLE
Changed the MIR to represent function declarations as Options

### PR DESCRIPTION
**Pull request by rybern**
See issue #538

The large diffs in the expect tests are because adding an option type adds a set of parenthesis to the SExp

### CODE REVIEW

**Comment by nhuurre** [comment]
Sorry, I should've reviewed this a month ago. Could you resolve the merge conflicts? This certainly improves the MIR.

**Comment by rybern** [comment]
No worries, thanks, I'll add this to my to do list.

**Comment by nhuurre** [comment]
Thanks. Is this waiting for #627 or did you forget to `make format`?

**Comment by rybern** [comment]
Ha yeah you caught me - I was waiting for #627 because I had trouble installing ocamlformat 0.8 because it's quite old.

**Review by nhuurre — APPROVED** [review]
Just needs a `dune promote`.

**Comment by rok-cesnovar** [comment]
Bumping this. @rybern do you have a few minutes to merge master in and run dune promote so we can merge this.

**Comment by rybern** [comment]
Ah, thanks Rok!

**Pull request merged**
