### PR TITLE
Handle integrate_1d's non-standard argument placement for pstream

### LINKED ISSUE #301: Add signatures for integrate_1d
here's the PR from Stan (no issue available describing the signatures or functionality, unfortunately): 
https://github.com/stan-dev/stan/pull/2627

Manual page: https://mc-stan.org/docs/2_20/functions-reference/functions-1d-integrator.html

This might be a good issue to generate an exemplar PR to use to document how to add a new function to Stan in stanc3. I'll also try to record myself programming it for documentation.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Closes #301 

@bbbales2 This fixes the issue for the model you mentioned [here](https://github.com/stan-dev/stanc3/issues/301#issuecomment-560026773). I was able to compile it succesfully with cmdstan.

I addeda a motherHOF.stan model that generates c++ code to cpp.expected so we now check the generated C++ for higher-order functions (The existing mother model only checks code gen for the algebra_solver).  I am not sure it covers all the cases, so I would appreciate if someone with more experience with them would check.

### CODE REVIEW

**Comment by bbbales2** [comment]
Thanks for doing this, I'll look at this soon, though I don't think I'm the right person for the map_rect or algebra_solver changes.

**Comment by bbbales2** [comment]
Should the integrate_1d tests go in: https://github.com/stan-dev/stanc3/blob/0ab51cf653a277d9a0d445c0493ebd9b48881b0c/test/integration/good/function-signatures/math/functions/integrate_1d.stan? I don't see why they should go with the other high order function tests, though I guess that keeps things in one place which is nice.

I think these are the full integrate_1d signatures.

Add this to the parameters block:
```
real x_r;
```

These are the tests for the model block:
```
real y_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0.0, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0, 1.0, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0.0, 1.0, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, x_r, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0, x_r, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, x_r, x_r, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, x_r, 1, x_d_r, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0, x_r, x_d_r, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, x_r, x_r, x_d_r, x_d_r, x_d_i);
```
```
real z_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0.0, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0, 1.0, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0.0, 1.0, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, x_r, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0, x_r, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, x_r, x_r, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, x_r, 1, x_d_r, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0, x_r, x_d_r, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, x_r, x_r, x_d_r, x_d_r, x_d_i, 1e-8);
```

These are the tests for the generated quantities block:
```
real y_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0.0, 1, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0, 1.0, x, x_d_r, x_d_i);
y_1d = integrate_1d(integrand, 0.0, 1.0, x, x_d_r, x_d_i);
real z_1d = integrate_1d(integrand, 0, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0.0, 1, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0, 1.0, x, x_d_r, x_d_i, 1e-8);
z_1d = integrate_1d(integrand, 0.0, 1.0, x, x_d_r, x_d_i, 1e-8);
```

**Comment by rok-cesnovar** [comment]
Thanks for the exhaustive list!

I will add them both in the file you  linked and the motherHOF. The one you linked isnt used to test c++ generated code. Just that stanc3 can compile them. With this PR we add the generated cpp for the MotherHOF model to the tests. Hopefully I am making some sense. Writing on my phone, can explain in more detail tomorrow if you need additional info.

**Comment by bbbales2** [comment]
Nah, that makes sense.

> I addeda a motherHOF.stan model that generates c++ code to cpp.expected so we now check the generated C++ for higher-order functions

I think the error only comes up if you actually tried to compile against the math library. This is checking that?

**Comment by rok-cesnovar** [comment]
I finally added your signatures to tests. Thanks again. These tests don't actually compile to model executables but check the outputed cpp. So once this gets in and anyone changes how the cpp for these functions generates that will be noticed.

**Comment by seantalts** [comment]
This looks good to me, though @bbbales2 is right that at some point we need to add a test that this does not choke the C++ compiler. I have something in Jenkins already that I think I just need to fix and then set to run on merge to master.

**Comment by seantalts** [comment]
Thanks very much for fixing this and adding the tests!

**Pull request merged**
