### PR TITLE
Fix #376. Hope @VMatthijs and Jenkins agree.

### LINKED ISSUE #376: C++ compile error for McElreath's logistic1.stan
See https://discourse.mc-stan.org/t/cmdstan-2-21-compile-map-rect-model-fails/11706

```
halair ~/scm/cmdstan (develop) $ make -j2 logistic1

--- Compiling, linking C++ code ---
/Library/Developer/CommandLineTools/usr/bin/clang++ -march=core2 -std=c++1y -Wno-unknown-warning-option -Wno-tautological-compare -Wno-sign-compare -D_REENTRANT      -I stan/lib/stan_math/lib/tbb_2019_U8/include -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.3 -I stan/lib/stan_math/lib/boost_1.69.0 -I stan/lib/stan_math/lib/sundials_4.1.0/include    -DBOOST_DISABLE_ASSERTS      -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o logistic1.o logistic1.hpp
In file included from logistic1.hpp:1:
In file included from stan/src/stan/model/model_header.hpp:4:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math.hpp:4:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/rev/mat.hpp:12:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat.hpp:71:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/fun/chol2inv.hpp:7:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/fun/mdivide_left_tri_low.hpp:6:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/fun/mdivide_left_tri.hpp:6:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/fun/promote_common.hpp:5:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/fun/promote_elements.hpp:4:
In file included from /Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/arr/fun/promote_elements.hpp:5:
/Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/scal/fun/promote_elements.hpp:24:48: error: no viable conversion from
      returned value of type 'const stan::math::var' to function return type 'double'
  inline static T promote(const S& u) { return u; }
                                               ^
/Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/arr/fun/array_builder.hpp:38:42: note: in instantiation of member
      function 'stan::math::promote_elements<double, stan::math::var>::promote' requested here
    x_.push_back(promote_elements<T, S>::promote(u));
                                         ^
logistic1.hpp:125:45: note: in instantiation of function template specialization
      'stan::math::array_builder<double>::add<stan::math::var>' requested here
        stan::math::array_builder<double>().add(lp).array()));
                                            ^
logistic1.hpp:143:8: note: in instantiation of function template specialization
      'logistic1_model_namespace::lp_reduce<stan::math::var, double, double>' requested here
return lp_reduce(beta, theta, xr, xi, pstream__);
       ^
/Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/rev/mat/functor/map_rect_reduce.hpp:112:23: note: in instantiation of
      function template specialization 'logistic1_model_namespace::lp_reduce_functor__::operator()<stan::math::var, double, double>'
      requested here
      vector_v fx_v = F()(shared_params_v, job_specific_params, x_r, x_i, msgs);
                      ^
/Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/rev/mat/functor/map_rect_concurrent.hpp:41:23: note: in instantiation of
      member function 'stan::math::internal::map_rect_reduce<logistic1_model_namespace::lp_reduce_functor__, stan::math::var,
      double>::operator()' requested here
      job_output[i] = ReduceF()(shared_params_dbl, value_of(job_params[i]),
                      ^
/Users/xitrium/scm/cmdstan/stan/lib/stan_math/stan/math/prim/mat/functor/map_rect.hpp:174:20: note: in instantiation of function
      template specialization 'stan::math::internal::map_rect_concurrent<1, logistic1_model_namespace::lp_reduce_functor__,
      stan::math::var, double>' requested here
  return internal::map_rect_concurrent<call_id, F, T_shared_param, T_job_param>(
                   ^
logistic1.hpp:288:28: note: in instantiation of function template specialization 'stan::math::map_rect<1,
      logistic1_model_namespace::lp_reduce_functor__, stan::math::var, double>' requested here
        lp_accum__.add(sum(map_rect<1, lp_reduce_functor__>(beta, theta, xr,
                           ^
logistic1.hpp:462:14: note: in instantiation of function template specialization
      'logistic1_model_namespace::logistic1_model::log_prob<false, false, stan::math::var>' requested here
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
             ^
/Users/xitrium/scm/cmdstan/stan/src/stan/model/model_base_crtp.hpp:95:50: note: in instantiation of function template specialization
      'logistic1_model_namespace::logistic1_model::log_prob<false, false, stan::math::var>' requested here
    return static_cast<const M*>(this)->template log_prob<false, false>(theta,
                                                 ^
logistic1.hpp:162:3: note: in instantiation of member function
      'stan::model::model_base_crtp<logistic1_model_namespace::logistic1_model>::log_prob' requested here
  ~logistic1_model() { }
  ^
1 error generated.
make: *** [logistic1] Error 1
```

### PR DESCRIPTION
**Pull request by seantalts**

### CODE REVIEW

**Comment by VMatthijs** [comment]
@seantalts , this seems right to me. However, it does mean that variables could get overpromoted to AD variables in function bodies if we don't use a AD level optimization. Currently, I believe that optimization would just get run inside each function body and in the main program in an intraprocedural way. Obviously, it'd be preferable to go towards interprocedural optimization in that respect. I guess we usually inline functions though, which would give our intraprocedural optimization more power.

**Comment by seantalts** [comment]
Sweet. So maybe it's safe to turn on the intraprocedural ad-level optimization by itself by default?

**Comment by seantalts** [comment]
Looks like not only is turning on autodiff level optimization good, but it got us a 9% speedup? https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-379/1/pipeline/46

Cheers to @VMatthijs and @rybern for this win!

**Comment by seantalts** [comment]
Ah, we were already at 2.5% speedup, so the current ad-level optimization got us an additional 6.5%. Still awesome! Really looking forward to getting more of these turned on by default.

**Pull request merged**
