### PR TITLE
Revert 521

### PR DESCRIPTION
**Pull request by rok-cesnovar**
This PR reverts #521 

There is nothing wrong with the stanc3 implementation itself, but rvalue seems to does have a performance penalty the way it is implemented right now. I will dig a bit more in the rvalue implementation if we can maybe not revert the stanc3 PR. If we can't find a solution, it will have to be reverted for the release.

### CODE REVIEW

**Comment by wds15** [comment]
Is there a stanc3 magic url I can use from this PR to test this out?

**Comment by rok-cesnovar** [comment]
Building https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3-test-binaries/detail/stanc3-test-binaries/130/pipeline

**Comment by nhuurre** [comment]
I was afraid of this. I assume the problem is that non-checking index access can return a reference/pointer but `rvalue()` must return a copy? Is [stan::math::get_base1](https://github.com/stan-dev/math/blob/develop/stan/math/prim/fun/get_base1.hpp) a lightweight alternative to `rvalue`? Stanc2 had that but I wasn't sure why.

**Comment by rok-cesnovar** [comment]
Could be yes. I was debating this with @t4c1 and the first thing that popped up was the checks, but commenting out checks made no difference.

**Comment by t4c1** [comment]
> I assume the problem is that non-checking index access can return a reference/pointer but rvalue() must return a copy?

I kinda doubt it. Usually it is faster to return scalars by value than by reference. It might make a difference for `var`. Anyway compilers are quite good at optimizing returns.

On the other hand I have no idea what it could be, so something I don't understand must be going on.

It might be worth trying `get_base1`. I have no idea if it will help, but at least its a bit simpler without those awkward index structs.

**Comment by rok-cesnovar** [comment]
Should we just merge this and go without this check feature for the release? And if we come up with something until Monday we merge that?

**Comment by rok-cesnovar** [comment]
@wds15  if you wish to confirm this one on your system:

STANC3_TEST_BIN_URL = https://jenkins.mc-stan.org/job/stanc3-test-binaries/130/artifact

**Comment by rok-cesnovar** [comment]
The simplest model where I can reproduce this issue is the non-vectorized Bernoulli example model.

```stan
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);  // uniform prior on interval 0,1
  for(i in 1:N) {
    y[i] ~ bernoulli(theta);
  }  
}

```

**Comment by rok-cesnovar** [comment]
Sebastian confirmed this fixes the perf. regression. Anyone wants to approve?

**Pull request merged**
