### PR TITLE
Change parameters to DataOnly inside generated quantities block

### PR DESCRIPTION
**Pull request by nhuurre**
issue #540 

There's also a problem with `map_rect` because it has a different interpretation what `DataOnly` means.
`DataOnly` just means there's no autodiff but `map_rect` expect the data to be persistent between iterations. We should probably add `StaticData` qualifier for that case.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
> `map_rect` expect the data to be persistent between iterations

If using MPI yes.

> We should probably add `StaticData` qualifier for that case.

That or refactor the MPI interface yes. I was thinking we could just add the requirement that non-literal indexing can not be used with map_rect inputs if using MPI. So x[0], x[1], y[0,0] would work but x[i] would not. Which would fix https://github.com/stan-dev/stanc3/issues/441
Would that work or would that be too confusing?

And once we move the copying to the model level we could also remove that restriction.

**Comment by bob-carpenter** [comment]
Yes, we defintely need to split `const data` from `data` or whatever we want to call it.  The former is for map_rect and the latter for ODE solvers, etc.

**Comment by bob-carpenter** [comment]
> I was thinking we could just add the requirement that non-literal indexing can not be used with map_rect inputs if using MPI. So x[0], x[1], y[0,0] would work but x[i] would not. Which would fix #441 Would that work? 

I think we'll still have problems with this:

```
cond ? x[0] : x[1]
```

**Comment by nhuurre** [comment]
Restricting the indexing of `map_rect` arguments is probably the best solution for the MPI static data issue. In any case, that is not a blocker for this PR. I mentioned it here only because I had to change a few of test files in `test/integration/bad/map_rect/`. Those tests check that certain uses of `map_rect` are invalid and they can no longer catch non-static data in generated quantities.

**Pull request merged**
