### PR TITLE
Use new STANC2=true flag in CmdStan instead of old performance-tests-cmdstan branch

### PR DESCRIPTION
**Pull request by seantalts**

### CODE REVIEW

**Comment by SteveBronder** [comment]
Think it just needs to be `stan::math::size`

**Comment by seantalts** [comment]
Thanks! I'm trying to get the Jenkins tests to fail with the correct failure before fixing the failure, haha.

**Comment by seantalts** [comment]
Okay the last one failed correctly, finally: https://jenkins.mc-stan.org/blue/organizations/jenkins/stanc3/detail/PR-439/5/pipeline

Added the change to stan::math::size and hopefully this should pass and be good to go.

**Comment by seantalts** [comment]
It's done! Anyone want to review?

**Comment by seantalts** [comment]
Okay, I'm just going to merge this for now since it's a tiny change source change and a Jenkins change we need for release and Steve already gave a conditional thumbs up. If anyone sees anything suboptimal with this in the future please feel free to comment.

**Pull request merged**
