### PR TITLE
Allow driver code to set printed argument list in generated hpp

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [x] OR, no user-facing changes were made

## Release notes

The generated `model_compile_info` will now feature arguments  passed in from stancjs

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
I’d like to write a good test for this before merging, I eyeballed that it looks correct

**Review by hsbadr — COMMENTED** [review]
@WardBrian This does print the flags in the compile info:
```r
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.0-37-g09a0377", "stancflags = O1"};
  }
  ```
  
It might be useful to add them with the version comment too:
```c++
// Code generated by stanc v2.30.0-37-g09a0377
```

**Review by hsbadr — COMMENTED** [review]
@WardBrian Would it make sense to unify how the flags are printed? For example, `stanc` binary gets `stancflags = --O1` while the JS generates `stancflags = O1`. Alternatively, you may mention that it's command line or JS in the model compile info.

**Comment by WardBrian** [comment]
@rok-cesnovar should be ready now. I would also like to include this in the patch release

**Review by rok-cesnovar — APPROVED** [review]
Great, thanks!

**Pull request merged**
