### PR TITLE
Start generating writes for transform_inits

### LINKED ISSUE #178: Fix transform_inits method in code gen
It should be writing to the `params_r__` input vector but is currently not. The param reading and unconstraining might be working correctly already.

### PR DESCRIPTION
**Pull request by seantalts**
Fixes #178

### CODE REVIEW

**Comment by VMatthijs** [comment]
This looks good, but has it been tested anywhere? Is it hard to do that?

**Comment by seantalts** [comment]
I wrote to @bob-carpenter asking if there was a good way to do it. It might just be a manual thing for now.

**Comment by bob-carpenter** [comment]
How can I help?

**Comment by seantalts** [comment]
Oh, just the email about how to test this. Looks like I just need to add a test that sets initial values on both an old and a new Stan program and see that they get the same results. Unfortunately that doesn't fit into any of the existing test paradigms we have right now... Maybe I will just test it manually and leave it not tested automatically for now. It's not like we're testing this automatically with stanc2 anywhere end to end.

**Comment by seantalts** [comment]
Tested this locally and it seemed to work, so merging for now.

**Pull request merged**
