### PR TITLE
Remove hacky array syntax parsing, improve error messages

### LINKED ISSUE #953: Incorrect parser errors on variable declarations
The way the parser handles the new array[] syntax leads to a _lot_ of errors all ending in the same state.

In parser.messages, we provide the error:

"Expected non-array type after array in return type."

for the sentence 
program: DATABLOCK LBRACE ARRAY LBRACK IDENTIFIER RBRACK REAL UPPER WHILE

the problem is, this sentence is equivalent to program: DATABLOCK LBRACE UPPER REAL WHILE WHILE in the parser's states.

This means the following program, which a user might reasonably create by misinterpretting multiple declarations:

```stan
data {
real x, int y;
}
```
gives the following unhelpful error:

```
Syntax error in 'bad_multiple_decl.stan', line 2, column 16 to column 17, parsing error:
   -------------------------------------------------
     1:  data {
     2:      real x, int y;
                         ^
     3:  }
   -------------------------------------------------

Expected non-array type after array in return type.
```

-----

This is tricky to fix. The "bit of a hack" we use to parse the new array syntax without making it a reserved word means that we basically can't write a good error message for this rule, because the parser ends in the same state (670) for too many different errors.

Additionally, the way we allow 'offset', 'multiplier' et al as identifiers, and actually parse most of the reserved words to then throw an error in the semantic check, makes the parser messages file very difficult to maintain: an input sentence like `data { real real x; }`
is parsed equivalently to a sentence like 
`data { real x y; }` and so the error has no idea that the type is wrong. It's recommended fix is to put a semicolon before the x, leaving you with `real real;`, which the semantic check would later complain about. The sentence Menhir generates as an example might have the token 'WHILE' or 'REAL' where one would reasonably expect an Identifier, and that's because we do ''allow'' those things as identifiers.

The most straightforward fix for this second issue is to not try to be as cute in the parser - even if we continue to allow offset/multiplier as identifiers, the reserved-words-caught-in-semantic-check method is not ideal. As for the first problem, I think it requires array as a reserved word to simplify the parsing logic sufficiently. I think this is important to address before the parser becomes very difficult to maintain

### PR DESCRIPTION
**Pull request by WardBrian**
While working on updating the Tuples PR, I realized that it's possible to resolve the shift/reduce conflict while still allowing `array` as an identifier, with a slightly different approach. This makes that PR easier, and greatly improves the ability to make error messages around declarations. See the test output for some examples/improvements. 

This is similar to how @rybern originally implemented it in https://github.com/stan-dev/stanc3/pull/708, with they key difference being that this uses precedence to resolve the conflict rather than reserving `array`. I believe it keeps/improves existing behavior, and until we can reserve array in 2.32 should be fine.

Closes #953. 

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Improve error messages for incorrect variable declarations.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rybern** [comment]
Great solution!

**Review by rok-cesnovar — APPROVED** [review]
Nice! Thanks!

**Comment by WardBrian** [comment]
@rok-cesnovar if we merge once tests pass this will make it into the 2.29 release candidate right?

**Comment by rok-cesnovar** [comment]
Yeah, we are still waiting for https://github.com/stan-dev/stan/pull/3095 for the release candidate anyways.

**Comment by WardBrian** [comment]
Great! I think its pretty unlikely this has any incompatibilities (the existing tests all either pass or fail like before, it's just message changes), but it's good it will be part of the RC right away

**Comment by rok-cesnovar** [comment]
Yes of course. We can never be too sure of anything :)

**Pull request merged**
