### PR TITLE
Add Nix expression and README section on Nix usage

### PR DESCRIPTION
**Pull request by rybern**
Getting the environment set up for Stanc3 with Opam seems to be a pain point for some would-be developers. I'm publishing the Nix expression that I use in case that's an easier alternative for anyone. See the README update for a short explanation of Nix usage.

### CODE REVIEW

**Comment by SteveBronder** [comment]
Odd, I installed nix and running `nix-build` I'm getting two errors on the tests

```
      menhir src/frontend/parsing_errors.ml
Read 497 sample input sentences and 497 error messages.
         ppx src/middle/Location.pp.ml (exit 1)
(cd _build/default && .ppx/eff24732fc4f7846ed05574216935c9a/ppx.exe --cookie 'library-name="middle"' -o src/middle/Location.pp.ml --impl src/middle/Location.ml -corrected-suffix .ppx-corrected -diff-cmd - -dump-ast)
File "src/middle/Location.ml", line 13, characters 11-33:
13 |     ignore (input_line_exn input)
                ^^^^^^^^^^^^^^^^^^^^^^
Error: Jane Street style: Ignored expression must come with a type annotation
         ppx src/middle/Stan_math_signatures.pp.ml
File "src/middle/Stan_math_signatures.ml", lines 3-9, characters 0-2:
3 | (** The "dimensionality" (bad name?) is supposed to help us represent the
4 |     vectorized nature of many Stan functions. It allows us to represent when
5 |     a function argument can be just a real or matrix, or some common forms of
6 |     vectorization over reals. This captures the most commonly used forms in our
7 |     previous signatures; there are a lot partially because we had a lot of
8 |     inconsistencies.
9 | *)
Warning 50: ambiguous documentation comment
      ocamlc src/middle/.middle.objs/byte/middle__UnsizedType.{cmi,cmo,cmt} (exit 2)
```


```
File "src/middle/UnsizedType.ml", line 63, characters 6-11:
63 |     | UReal, UInt -> true
           ^^^^^
Error: This pattern matches values of type t
       but a pattern was expected which matches values of type
         Core_kernel.Int.t = int
                       
```

Does this need to pinned versions of the different dependencies?

**Comment by rybern** [comment]
Glad you tried it out, I will investigate

**Comment by SteveBronder** [comment]
np! And yeah the nix setup looks very nice if we can get it all tidied up. Was much easier to run and check! Also did not goof with my main system stuff which was nice

**Comment by idontgetoutmuch** [comment]
```
bash-3.2$ nix-shell -I nixpkgs=https://github.com/NixOS/nixpkgs/archive/20.03.tar.gz --command "dune build --profile release @runtest"
      menhir src/frontend/parsing_errors.ml
Read 497 sample input sentences and 497 error messages.
File "src/middle/Stan_math_signatures.ml", line 3, characters 0-407:
3 | (** The "dimensionality" (bad name?) is supposed to help us represent the
4 |     vectorized nature of many Stan functions. It allows us to represent when
5 |     a function argument can be just a real or matrix, or some common forms of
6 |     vectorization over reals. This captures the most commonly used forms in our
7 |     previous signatures; there are a lot partially because we had a lot of
8 |     inconsistencies.
9 | *)
Warning 50: ambiguous documentation comment
```

**Comment by rybern** [comment]
Thanks @idontgetoutmuch - that's what I get as well, using nixpkgs 20.03.

It's odd that @SteveBronder appears to have version differences using the default nixpkgs, but in any case I suppose I need to to start pinning the dependencies.

**Comment by rybern** [comment]
@SteveBronder Would you mind running that command again when you get the chance?

**Comment by idontgetoutmuch** [comment]
One of my more nix knowledgeable colleagues commented:

> Instead of using builtins.path , maybe they could use something such as sourceByRegexp from the nixpkgs lib: https://github.com/NixOS/nixpkgs/blob/master/lib/sources.nix#L85

> They really have to be careful with <nixpkgs> since it is "generally" not reproducible. They should instead pin the nixpkgs version they want to use. They could do it manually with buildins.fetchTarball , use Niv or read the flake blog post :wink:

**Comment by rybern** [comment]
Thanks @idontgetoutmuch and your colleague! I will check out sourceByRegexp. I have pinned nixpkgs now using fetchTarball. It is amazing that Tweag addressed this issue with flakes two days ago, they look outstanding, but I'll hold off for now because I don't want to force users to use an experimental Nix branch.

**Comment by rybern** [comment]
Thanks Steve!

**Pull request merged**
