### PR TITLE
Feature/issue 535 hmm

### PR DESCRIPTION
**Pull request by charlesm93**
## Summary

Solves issue #535 and exposes a suite of functions in the stan-math library for hidden Markov models with a discrete latent variable. The functions are:
* `hmm_marginal()`
* `hmm_hidden_state_prob()`
* `hmm_latent_rng`

Typically, the first function is used on the R.H.S of the `target`. The observed data is however not directly passed as an argument, which is why it does not have an lpdf suffix. `hmm_hidden_state_prob` is not differentiable: hence it cannot accommodate parameter-dependent arguments, except in the rng block.

## Tests

* `integration/good/functions-signature/distributions/multivariate/continuous/hmm_marginal.stan`
* `integration/good/functions-signature/math/functions/hmm_hidden_states_prob.stan`
* `integration/bad/hmm_hidden_state_prob/`
* `integration/good/functions-signature/distributions/rngs.stan`

For `hmm_hidden_state_prob`, I create a suite of tests to check the parser returns an error message when we pass in a parameter-dependent argument.

## Copyright

Copyright holder: Charles Margossian, Columbia University

The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
- Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by charlesm93** [comment]
-_- not sure how to read the error message picked up by the continuous integration. The reported errors occur where you would expect them, i.e. under the `bad` directory, but this might not even be what the tests are complaining about.

**Comment by rok-cesnovar** [comment]
Run "dune runtest" in the top stanc3 folder. Then dune promote. The /good expected are missing.

**Comment by rok-cesnovar** [comment]
That will also add the signatures.

**Comment by charlesm93** [comment]
@rok-cesnovar to the rescue! I did as you said.

**Comment by bob-carpenter** [comment]
I'm seriously not qualified to review OCaml yet.  I can do it in a pinch if you can't find anyone else.

**Comment by charlesm93** [comment]
@rok-cesnovar or @SteveBronder would one of you mind reviewing this pull request?

**Comment by rok-cesnovar** [comment]
The 8 Ocaml lines look great. Will look at the tests models tomorrow and review.

**Pull request merged**
