### PR TITLE
Expose Lambert W functions

### PR DESCRIPTION
**Pull request by Christopher22**
This pull request "fixes" #571 by exposing the newly implemented 'lambert_w0' and 'lambert_wm1' functions implemented in [math](https://github.com/stan-dev/math/pull/1882).

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Hi @Christopher22,

please run
```
dune runtest
dune promote
```
in your stanc3 folder.

**Comment by rok-cesnovar** [comment]
And obviously commit & push what will be generated.

**Comment by nhuurre** [comment]
We have function signature tests in [test/integration/good/function-signatures/math/functions](https://github.com/stan-dev/stanc3/tree/master/test/integration/good/function-signatures/math/functions) and [-/matrix](https://github.com/stan-dev/stanc3/tree/master/test/integration/good/function-signatures/math/matrix)

I'm not sure how complete those are but could you add these functions? Just copy `cos.stan` file in the folder and change the cosines to lambert_w.

**Comment by Christopher22** [comment]
Sure, I will do that. Thanks for highlighting the corresponding unit tests!

**Comment by Christopher22** [comment]
> 
> 
> Hi @Christopher22,
> 
> please run
> 
> ```
> dune runtest
> dune promote
> ```
> 
> in your stanc3 folder.

Thank you for the hint! Is there anywhere a description in the documentation of all the requirements? Currently, my local dune is failing to test even the unchanged master branch...

**Comment by Christopher22** [comment]
Probably, it is just a problem with an too recent version of some dependency:

"Error (alert deprecated): module Core_kernel.Unix
[since 2020-03] Core_kernel shadows Unix. Use Core.Unix, which overrides some of Unix's behavior. If necessary, Unix is available and unshadowed as Caml_unix."

**Comment by rok-cesnovar** [comment]
https://github.com/stan-dev/stanc3#getting-development-on-stanc3-up-and-running-locally points to a script that installs all dependencies. Try that first if you haven't already.

**Comment by SteveBronder** [comment]
You can also use the nix build which I found a bit simpler

https://github.com/stan-dev/stanc3#using-nix-to-build-test-and-run

**Comment by Christopher22** [comment]
Good advice, @SteveBronder . Setting up the VM and trying to build with opam cost me 6 hours yesterday - there seems to be a bug with recent gcc versions... Nix worked like a charm. 

I added now both the generated dune files as the corresponding unit tests. :)

**Comment by rok-cesnovar** [comment]
> Setting up the VM and trying to build with opam cost me 6 hours yesterday

Sorry to hear that. Dont want to take more of your time on this but can you explain what you tried so we can reproduce and hopefully also fix this.

You install a Linux VM and followed the linked script and that failed?

Will review this shortly.

**Comment by Christopher22** [comment]
Well, its not your fault nor of the quite useful utility scripts. :) As far as I understood it in the end, ocam failed to build the required older version of ocaml with the gcc version installed. There was a linker error regarding "multiple definition of `caml debug_info';". I would assume that this results from the fact that GCC has defaulted to -fcommon for many years and GCC 10 is changing the default to -fno-common. But that is just a guess.

**Pull request merged**
