### PR TITLE
Update js_of_ocaml to 4.1.0

### PR DESCRIPTION
**Pull request by WardBrian**
This bumps us from 3.11 to 4.1, which includes a fix for an inlining issue that can affect performance that @andrjohns found discussions of. Some quick local tests suggested that this is about 10% faster just from updating.

@serban-nicusor-toptal - I think to actually get this going in our CI we need to re-build our docker images, right?

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Updated the OCaml-to-JS compiler used to create stanc.js

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian that's [correct](https://github.com/stan-dev/ci-scripts/tree/master/docker/stanc3), I'll build them later when I get home.

**Comment by serban-nicusor-toptal** [comment]
I've pushed two new images:
- stanorg/stanc3:debian-windows-js4.1.0 ( I saw that this one also runs the `install_js_deps` script )
- stanorg/stanc3:debian-js4.1.0

**Comment by WardBrian** [comment]
@serban-nicusor-toptal after switching the images getting a CI failure `dune: not found`

**Comment by serban-nicusor-toptal** [comment]
That must be because of the opam install I think, I'll rebuild and test locally then push a new one.

**Comment by serban-nicusor-toptal** [comment]
@WardBrian everything should be working fine now!

**Comment by WardBrian** [comment]
Great, thanks!

Do we rename the image to `debian` or should we just merge with the Jenkinsfile changed?

**Comment by serban-nicusor-toptal** [comment]
I think it's fine to leave it as is, I've used `debianfi` after the migration to Flatiron CI. We also have the latest state in ci-scripts repo.

**Comment by WardBrian** [comment]
Great, thanks! 

I’m considering another update soon (to OCaml 4.14, the last of the 4.x releases) so we will probably change the images again at that point

**Pull request merged**
