### PR TITLE
Array type syntax

### PR DESCRIPTION
**Pull request by rybern**
Please see #669 for a description and discussion history for this PR. I'm reopening it to fix a GitHub issue with a bad diff.

### CODE REVIEW

**Comment by seantalts** [comment]
...very confused about why this still has the issue.

**Comment by seantalts** [comment]
I think maybe that "destructive merge" commit wasn't properly a merge or something. I'm trying to fix it...

**Comment by seantalts** [comment]
Okay, I think I got a good branch up. It's on this repo as `array-type-syntax-fix-merge`. I think it makes sense to keep you as the PR author; would you mind checking out that branch from stan-dev, pushing it to your fork, and then changing this PR to be based from that branch on your fork? :D Sorry about that, totally my bad on the merge commit. Not sure what I did wrong there, must have accidentally exited the merging state somehow.

**Comment by rybern** [comment]
Gotcha, all set on a new PR

**Pull request closed without merging**
