### PR TITLE
Build backwards-compatible Mac executables on flatiron mac

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [ ] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

CI change, build backwards-compatible Mac executables on flatiron mac.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
@serban-nicusor-toptal did you confirm the built binaries from this run on the old gelman-mac?

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian I think it's ready for review.
I ran a test job here: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/PR-1255/2/artifacts
Where you can find the binary, I ran it on the gelman mac ( --help ) and it seems to work fine.

**Comment by serban-nicusor-toptal** [comment]
I will give it another try on the `old-imac` instance.

**Comment by WardBrian** [comment]
Awesome, thanks!

**Review by WardBrian — APPROVED** [review]

**Comment by serban-nicusor-toptal** [comment]
Thank you too for the work on this! 
Will merge the PR now.

**Pull request merged**
