### PR TITLE
Bugfix/elementwise pow and empty matrices

### LINKED ISSUE #661: Elementwise pow functions not compiling at the C++ level
Unfortunately, this is a bug in the release version which will most likely warrant a hotfix release.

This test model https://github.com/stan-dev/stanc3/blob/master/test/integration/good/function-signatures/math/matrix/elementwise_pow.stan compiles to C++, but the generated C++ does not compile with: 

```cpp
examples/bugs/bug.hpp:3464:41: note:   ‘std::vector<std::vector<std::vector<Eigen::Matrix<double, 1, -1> > > >’ is not derived from ‘const Eigen::ArrayBase<Derived>’
 3464 |         pow(p_row_vector_array_3d, d_int),
      |                                         ^
In file included from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Core:533,
                 from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4:
stan/lib/stan_math/lib/eigen_3.3.7/Eigen/src/Core/GlobalFunctions.h:161:3: note: candidate: ‘template<class Scalar, class Derived> typename Eigen::internal::enable_if<((! Eigen::internal::is_same<typename Derived::Scalar, Scalar>::value) && Eigen::internal::has_ReturnType<Eigen::ScalarBinaryOpTraits<Scalar, typename Derived::Scalar, Eigen::internal::scalar_pow_op<Scalar, typename Derived::Scalar> > >::value), const Eigen::CwiseBinaryOp<Eigen::internal::scalar_pow_op<Scalar, typename Eigen::internal::traits<_Rhs>::Scalar>, const typename Eigen::internal::plain_constant_type<Derived, Scalar>::type, const Derived> >::type Eigen::pow(const Scalar&, const Eigen::ArrayBase<ExponentDerived>&)’
  161 |   pow(const Scalar& x, const Eigen::ArrayBase<Derived>& exponents)
      |   ^~~
stan/lib/stan_math/lib/eigen_3.3.7/Eigen/src/Core/GlobalFunctions.h:161:3: note:   template argument deduction/substitution failed:
examples/bugs/bug.hpp:3464:41: note:   mismatched types ‘const Eigen::ArrayBase<ExponentDerived>’ and ‘const int’
 3464 |         pow(p_row_vector_array_3d, d_int),
      |                                         ^
In file included from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Core:533,
                 from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4:
stan/lib/stan_math/lib/eigen_3.3.7/Eigen/src/Core/GlobalFunctions.h:169:3: note: candidate: ‘template<class Derived> const Eigen::CwiseBinaryOp<Eigen::internal::scalar_pow_op<typename Derived::Scalar, typename Eigen::internal::traits<T>::Scalar>, const typename Eigen::internal::plain_constant_type<Derived, typename Derived::Scalar>::type, const Derived> Eigen::pow(const typename Derived::Scalar&, const Eigen::ArrayBase<Derived>&)’
  169 |   pow(const typename Derived::Scalar& x, const Eigen::ArrayBase<Derived>& exponents)
      |   ^~~
stan/lib/stan_math/lib/eigen_3.3.7/Eigen/src/Core/GlobalFunctions.h:169:3: note:   template argument deduction/substitution failed:
examples/bugs/bug.hpp:3464:41: note:   mismatched types ‘const Eigen::ArrayBase<Derived>’ and ‘const int’
 3464 |         pow(p_row_vector_array_3d, d_int),
      |                                         ^
examples/bugs/bug.hpp:3468:42: error: no matching function for call to ‘pow(const std::vector<std::vector<std::vector<Eigen::Matrix<double, 1, -1> > > >&, double&)’
 3468 |         pow(d_row_vector_array_3d, p_real),
      |                                          ^
In file included from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Core:96,
                 from stan/lib/stan_math/lib/eigen_3.3.7/Eigen/Dense:1,
                 from stan/lib/stan_math/stan/math/prim/fun/Eigen.hpp:22,
                 from stan/lib/stan_math/stan/math/rev.hpp:4,
                 from stan/lib/stan_math/stan/math.hpp:19,
                 from stan/src/stan/model/model_header.hpp:4:
/usr/include/c++/9/complex:1889:5: note: candidate: ‘template<class _Tp, class _Up> std::complex<typename __gnu_cxx::__promote_2<_Tp, _Up>::__type> std::pow(const std::complex<_Tp>&, const std::complex<_Up>&)’
```
The issue is the `using std::pow` in the generated code model code. Removing that fixes it, but need to double-check that does not corrupt anything else.

### LINKED ISSUE #662: Can't construct empty matrices
Now trying to compile all good tests in stanc3 uncovered that
```
transformed data {
  matrix[2,0] td_mat20;
  td_mat20 = [ [], [] ];
}
```
generates
```cpp
 assign(td_mat20, nil_index_list(), stan::math::to_matrix(
        stan::math::array_builder<Eigen::Matrix<double, 1, -1>>()
        .add(stan::math::to_row_vector(stan::math::array_builder<double>()
        .add().array())).add(stan::math::to_row_vector(
        stan::math::array_builder<double>().add().array())).array()),
        "assigning variable td_mat20");
```
but .add() is not a valid call. It should be add(0). This bug was also present in 2.23 so it does not seem as urgent, but if someone has an idea, we can fix it for 2.24.1

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Fixes #661 and fixes #662 

All models in test/integration/good compile with these changes

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This is ready for review.

**Comment by bbbales2** [comment]
@rybern can you get this?

The fix for #661 is adding `using stan::math::pow` alongside `using std::pow` to the generated code. If you trust (word of the day on the Gelblog) me on this statement you can avoid the details of why that is the case.

**Comment by andrjohns** [comment]
@rok-cesnovar  Does this also fix the code gen issue with ```real .^ real```?

**Comment by andrjohns** [comment]
I think the issue is caused by this line [here](https://github.com/stan-dev/stanc3/blob/master/src/stan_math_backend/Expression_gen.ml#L223)
```
  | EltPow ->
      fun ppf es -> pp_scalar_binary ppf "(%a@ *@ %a)" "pow(@,%a,@ %a)" es
```

I put the wrong operator in that first set of brackets, it should be ```^``` instead of ```*```

**Comment by rok-cesnovar** [comment]
Indeed, will fix that as well.

**Comment by rok-cesnovar** [comment]
Anyone has time to review this?

**Comment by rok-cesnovar** [comment]
Thanks! Will merge and then run all compilatiin tests tomorrow again. Then we can release the hotfix.

**Pull request merged**
