### PR TITLE
[Jenkins] See if we can graph our model coverage over time

### PR DESCRIPTION
**Pull request by seantalts**
(git branch based on #149 )

### CODE REVIEW

**Comment by VMatthijs** [comment]
Why does this PR look like it's touching lots of files? Didn't your previous PR already make those changes?

**Comment by seantalts** [comment]
Yes, I'm pretty confused about that too. I'm not sure if it's a github fuckup or what.

**Comment by seantalts** [comment]
Looks like it might just be github out of date:

```
hal ~/scm/stanc3 (jenkins-graph-model-passing) $ git diff --stat origin/master
 Jenkinsfile | 52 ++++++++++++++++++++++++++++++++++------------------
 1 file changed, 34 insertions(+), 18 deletions(-)
```

**Comment by seantalts** [comment]
Merging master in fixed the github UI :)

**Comment by VMatthijs** [comment]
@seantalts , where can I see this graph? I'm so curious.

**Comment by seantalts** [comment]
Well the graph is quite boring right now but you can see it on the build for `master` for stanc3: 
http://jenkins.mc-stan.org:8080/job/stanc3/job/master/

I'm going to try embedding it on the README somewhere...

**Pull request merged**
