### PR TITLE
[codegen] simplify indexed C++ generation

### PR DESCRIPTION
**Pull request by seantalts**

### CODE REVIEW

**Comment by seantalts** [comment]
[built on top of #155]

**Comment by seantalts** [comment]
I'm not sure this one is a good idea to do now; I could just drop it. I think the `assign` and `rvalue` calls are safer.

**Comment by VMatthijs** [comment]
It seems to me like @bob-carpenter  would be the right person to review this.

**Comment by seantalts** [comment]
Don't worry about taking a look at this - it will be superceded by https://github.com/stan-dev/stanc3/issues/232. Closing.

**Pull request closed without merging**
