### PR TITLE
Add signatures and tests for beta and binary_log_loss

### PR DESCRIPTION
**Pull request by andrjohns**
This PR adds the signatures and tests for the vectorised binary versions of the ```beta``` and ```binary_log_loss``` functions.

I've also checked that they compile locally (phew)

### CODE REVIEW

**Comment by andrjohns** [comment]
Hey @rok-cesnovar, I'm planning on continuing to add these signatures/tests in pairs. Would you prefer more functions added in a given PR? Also, would it be better to submit the PRs as they're ready or wait until a previous one has been approved?

**Comment by rok-cesnovar** [comment]
@andrjohns I am fine with pairs, but 3-5 work for me as well. Whatever you prefer.  Will double-check that expressions work with these (added signatures now means the function gets tested for Eigen expression inputs in stan-dev/stan) tomorrow and then merge. 

Feel free to open as many PRs as you like! Thanks for doing these!

**Comment by bbbales2** [comment]
@andrjohns Can you add back the release notes and license boilerplate stuff? (just do a new pull and copy from there)

**Comment by rok-cesnovar** [comment]
@bbbales2 Bob raised that once and the conclusion was that Github lists somewhere in their rules (can't remember where exactly) that by submitting a PR to a repo you automatically agree to submit under the license of that repo.

We can add someting to the PR template regardless (at least a note that by  submitting a PR you automatically agree that you submit under the BSD-3 license).

**Comment by bbbales2** [comment]
Oh okay. If it's good enough for Github it's good enough for me.

**Review by rok-cesnovar — APPROVED** [review]
Looks great. Thanks Andrew!

I tested that expressions also work with these new signatures.

**Pull request merged**
