### PR TITLE
Add GLM broadcasting signatures

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Adds the following GLM signatures that were added in Stan Math in https://github.com/stan-dev/math/pull/1389

```
real normal_id_glm_lpdf(real, matrix, real, vector, vector)
real normal_id_glm_lpdf(real, matrix, vector, vector, vector)
real normal_id_glm_lpdf(vector, row_vector, real, vector, vector)
real normal_id_glm_lpdf(vector, row_vector, vector, vector, vector)
real bernoulli_logit_glm_lpmf(int, matrix, real, vector)
real bernoulli_logit_glm_lpmf(int, matrix, vector, vector)
real bernoulli_logit_glm_lpmf(int[], row_vector, real, vector)
real bernoulli_logit_glm_lpmf(int[], row_vector, vector, vector)
real poisson_log_glm_lpmf(int, matrix, real, vector)
real poisson_log_glm_lpmf(int, matrix, vector, vector)
real poisson_log_glm_lpmf(int[], row_vector, real, vector)
real poisson_log_glm_lpmf(int[], row_vector, vector, vector)
real neg_binomial_2_log_glm_lpmf(int, matrix, real, vector, real)
real neg_binomial_2_log_glm_lpmf(int, matrix, vector, vector, real)
real neg_binomial_2_log_glm_lpmf(int[], row_vector, real, vector, real)
real neg_binomial_2_log_glm_lpmf(int[], row_vector, vector, vector, real)
```

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
We also need to update the GPU GLM table but I will do that in a separate PR.

**Comment by seantalts** [comment]
Thanks! need to `dune runtest; dune promote` ;)

**Comment by rok-cesnovar** [comment]
Argh, what a noob.

**Comment by seantalts** [comment]
Haha, this still happens to me as well. I would consider adding the entire `dune runtest` to the git hook, but it takes so long...

**Pull request merged**
