### PR TITLE
Add suffix to python kwrds 410

### PR DESCRIPTION
**Pull request by adamhaber**
- `await` and `async` are now in the keywords list.
- Code_gen had indentation problem with user defined functions, should be OK now.
- `Lit` removed from `translate_funapps_and_kwrds`
- User defined function properly handled (I hope) by checking all strings in `p.functions_block` and adding a case for `FunApp (UserDefined` in  `translate_funapps_and_kwrds`.

Following the discussion in #410 , the situation in which the Stan program contains both `lambda` and `lambda_` is not handled.

### CODE REVIEW

**Comment by adamhaber** [comment]
Thanks for the helpful suggestion!

This adds an extra empty line between imports and class definition (in models without user defined function), so I've promote some of the earlier .py files.

**Comment by adamhaber** [comment]
Removed WIP - I think this can be merged and we can handle the `lambda`/`lambda_` case later.

**Comment by nhuurre** [comment]
Double underscore suffix is reserved in Stan but doesn't have special meaning in Python. You can rename `lambda -> lambda__` to avoid potential conflict with `lambda_`.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by adamhaber** [comment]
Do you mean changing `let kwrds_suffix = "_"` to `let kwrds_suffix = "__"`? AFAIU, the problem with adding a suffix is quite general - whichever suffix we chose, if the original program has both `python_keyword` and `python_keyword+our_suffix` as identifiers, we're going to have a problem... right? OTOH, this may be too much of a corner case, and we can perhaps warn/fail if that's the case, and of course add this to the stan2tfp docs.

**Comment by nhuurre** [comment]
Yes, I mean `let kwrds_suffix = "__"`
The original program cannot have any identifiers with `__` suffix because its reserved for internal use. (Try it.)
A warning may be necessary when renaming data or parameters because those change input/output behavour.
Sent with [ProtonMail](https://protonmail.com) Secure Email.

**Comment by adamhaber** [comment]
> Yes, I mean `let kwrds_suffix = "__"`
The original program cannot have any identifiers with `__` suffix because its reserved for internal use. (Try it.)

Oh great, I didn't know that... thanks!

**Comment by adamhaber** [comment]
Hmm, probably missing something very trivial, but for some reason the warning from [here](https://github.com/stan-dev/stanc3/blob/b8698864f00bf887f38686eeee162b00be2d6cd5/src/frontend/Semantic_check.ml#L599) is added to the generated TFP code...

**Comment by adamhaber** [comment]
Pushed the new python_kwrds.py file, now including the warning. 

Perhaps that's a problem that should be handled at the level of the stan2tfp interface, and we're OK with the warning to be included in the .py file at the moment?

**Comment by nhuurre** [comment]
This has been inactive for a while. If there's nothing more you want to add could you resolve the conflicting `dune` file and we can merge this?

The general problems with frontend warnings are beyond the scope of this. Including them in the `.py` is fine for now. (Although, we now have operator `%/%` for integer division. Tests models should use that unless explicitly testing the warning.)

The identifier warnings generated in `tfp_backend/Transform_mir.ml` are a different matter. I think either of the following options is fine:
* prefix the warning with `# ` so that it becomes a comment (rather than a syntax error) in the py file
* print it with `Fmt.epr`. It's the same as `Fmt.pr` but prints to the error stream instead of the output stream. That should show up in the console but not go to the output file.

**Comment by adamhaber** [comment]
> This has been inactive for a while. If there's nothing more you want to add could you resolve the conflicting dune file and we can merge this?

Done.

> The general problems with frontend warnings are beyond the scope of this. Including them in the .py is fine for now.

Do such warnings always occur before the actual generated TFP code? If so, that makes fixing this at the interface level (like [stan2tfp](https://github.com/adamhaber/stan2tfp)) relatively easy. It's more of a workaround than a solution, though.   

> print it with Fmt.epr

Thanks, fixed it.

**Comment by rok-cesnovar** [comment]
> it's almost as if you're the only one here who remembers to run `make format`

Guilty as charged :) 

Offtopic on this PR but would anyone oppose making `make format` a step in the Jenkins CI? Either: 
- fail if running make format produces any changes
- push make format changes automatically

Maybe the first one would be better for Git history?

**Pull request merged**
