### PR TITLE
Fixing semantic check to accept _propto distributions

### PR DESCRIPTION
**Pull request by VMatthijs**
This addresses issue https://github.com/stan-dev/stanc3/issues/63 .

### CODE REVIEW

**Comment by seantalts** [comment]
What do you think of this:

```ocaml

(** Name manging to get propto versions of distributions to also type check *)
let remove_propto_infix suffix ~str =
  str
  |> String.chop_suffix ~suffix:(proportional_to_distribution_infix ^ suffix)
  |> Option.map ~f:(fun x -> x ^ suffix)

let propto_name_manging (name : string) =
  let suffices = ["_log"; "_lpdf"; "_lpmf"] in
  List.map ~f:(remove_propto_infix ~str:name) suffices @ [Some name]
  |> List.filter_opt |> List.hd_exn

let%expect_test "propto name mangling" =
  propto_name_manging "normal_propto_lpdf" |> print_string ;
  propto_name_manging "normal_lpdf" |> ( ^ ) "; " |> print_string ;
  propto_name_manging "normal" |> ( ^ ) "; " |> print_string ;
  [%expect {| normal_lpdf; normal_lpdf; normal |}]

```

**Comment by seantalts** [comment]
Or like, any of the ideas contained therein. I wanted to see if I could figure out another way to write it, not sure this is a win. @enetsee may have other ideas. We can merge it for now and keep working at it :)

**Comment by enetsee** [comment]
Doing this in OCaml using the standard library + Core is a bit ugly:

```ocaml
let propto_name_mangling name = 
  Option.(
    first_some 
      (first_some 
        (remove_propto_infix name ~suffix:"_log")
        (remove_propto_infix name ~suffix:"_lpdf")
      )
      (remove_propto_infix name ~suffix:"_lpmf")
    |> value ~default:name
  )
```
I would be inclined to define the flipped version of `first_some` (which is called `orElse` in F#): 

```ocaml
let propto_name_mangling2 name = 
  let or_else y x = Option.first_some x y in
  Option.(
    remove_propto_infix name ~suffix:"_log"
    |> or_else (remove_propto_infix name ~suffix:"_lpdf")
    |> or_else (remove_propto_infix name ~suffix:"_lpmf")
    |> value ~default:name
  )
```

**Comment by seantalts** [comment]
That looks good to me, thank you! I'm gonna add or_else to some kind of Utils module inside Middle (for now).

**Comment by VMatthijs** [comment]
That sounds like a good idea. I also notice that I wrote `name_manging` rather than `name_mangling`.

**Pull request merged**
