### PR TITLE
Check for out-of-bounds array access

### LINKED ISSUE #489: Eigen out of bounds access error with simple model
Here is the model:
```
transformed data {
  vector[1] y = to_vector({ 1.0 });
}

parameters {
  real mu;
}

model {
  y[0] ~ normal(mu, 1.0);
}
```

If I build and run it:
```
./model sample
```

I get an Eigen out of bounds error and the program stops:
```
model: stan/lib/stan_math/lib/eigen_3.3.3/Eigen/src/Core/DenseCoeffsBase.h:162: Eigen::DenseCoeffsBase<type-parameter-0-0, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Eigen::Matrix<double, -1, 1, 0, -1, 1>, 0>::operator[](Eigen::Index) const [Derived = Eigen::Matrix<double, -1, 1, 0, -1, 1>, Level = 0]: Assertion `index >= 0 && index < size()' failed.
Aborted (core dumped)
```

There should be some sort of Stan out of bounds access error I'm pretty sure. This is from cmdstan in develop. I assume this is a compiler thing, but maybe it is math somewhere. Can move the issue if that is the case.

### PR DESCRIPTION
**Pull request by nhuurre**
Fixes #489 by forcing the use of `stan::model::rvalue()` instead of direct access. As far as I know that doesn't incur any performance penalty beyond the range check.

The range check is still skipped for compiler generated indexing as those are likely to be correct.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@SteveBronder you have been working with rvalue at the stan level. Want to comment on performance? The code change is simple and looks good to me.

**Comment by rok-cesnovar** [comment]
@bob-carpenter @SteveBronder @t4c1 Just want to double-check with you guys on this one. Does forcing the use of `stan::model::rvalue()` instead of direct access incur any performance penalty?

**Comment by t4c1** [comment]
I think it should not.

**Comment by rok-cesnovar** [comment]
@nhuurre please resolve the conflict when you have the time. Then its good to go.

**Pull request merged**
