### PR TITLE
fix inlining of unnormalized functions

### LINKED ISSUE #729: lupdf breaks function inlining
Optimizer does not handle the newly added unnormalized density functions correctly.
This program normally compiles correctly but generates invalid C++ when transpiled with `stanc --O`
```stan
functions {
    real foo_lpdf(real x) {
        return normal_lupdf(x| 5, 10);
    }
}
parameters {
    real x;
}
transformed parameters {
    real ll = foo_lpdf(x);
}
model {
    target += ll;
}
```
The problem is that the function inlining optimization pass simply replaces `foo_lpdf` call with the function body and produces
```stan
transformed parameters {
    real ll = normal_lupdf(x| 5, 10);
}
```
but `_lupdf`s cannot appear outside of the model block. The correct behavior is to convert all inner unnormalized `_lupdf` calls to normalized `_lpdf` calls. 
```stan
transformed parameters {
    real ll = normal_lpdf(x| 5, 10);
}
```
The naive replacement is correct when the function call that is being inlined has `_lupdf` suffix.
```stan
model {
    real ll = foo_lupdf(x); // ok to inline without change
    target += ll;
}
```
Right now the inlining pass does not recognize it at all.

### PR DESCRIPTION
**Pull request by nhuurre**
Fix #729 

## Release notes

Fix a optimization bug in handling of unnormalized distributions.

## Copyright and Licensing

Copyright holder: Niko Huurre
By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — COMMENTED** [review]
Just one minor comment from me.

@rybern mind reviewing this whenever you have time? Thanks!

**Comment by rybern** [comment]
@rok-cesnovar will do

**Comment by rybern** [comment]
Implementation looks good, but I raised some questions about the approach in #729.

**Review by rybern — APPROVED** [review]
LGTM

**Pull request merged**
