### PR TITLE
Move docker images used in CI to stanorg account

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Replaces all references to Docker Hub for andrjohns images with stanorg.
#974 

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
I'll build and push the rest to `stanorg`.
Does it make any sense to set up and CI to build the images when there are changes to `dockerfile/windows` for example? I would do it so we have less to worry about.

**Comment by WardBrian** [comment]
If we’re building the images would we still want to maintain a docker folder here? I think just the scripts would be enough them?

**Comment by serban-nicusor-toptal** [comment]
I would say we need it as it defines the build steps of the docker build process, else I would either separate them into another repo or template them on the fly.

**Comment by WardBrian** [comment]
Feels like they could live in the ci-scripts repo if we moved to that system. It can be a separate PR though

**Comment by serban-nicusor-toptal** [comment]
`debian` and `debian-windows` pushed to Docker Hub.
If these images are used only in the CI, we can surely move them to ci-scripts ( will do another PR ).

**Comment by WardBrian** [comment]
Great!

The follow on PR can also remove the comment in stanc.ml which is great.

**Comment by WardBrian** [comment]
Any merit to leaving that comment in during the merge to test all the non-x86 binaries?

**Comment by serban-nicusor-toptal** [comment]
Well we can do it to be extra sure that everything works right after the merge.

**Comment by WardBrian** [comment]
If we're doing a follow on PR to remove the dockerfiles (them being moved to ci-scripts) we can remove it then, yes. Otherwise this seems good to me.

**Pull request merged**
