### PR TITLE
Feature/446 add reverse

### LINKED ISSUE #446: add signatures for reverse
In https://github.com/stan-dev/math/pull/1650 I added the implementation of reverse. We should expose the following signatures:
```
vector reverse(vector)
row_vector reverse(row_vector)
int[] reverse(int[])
real[] reverse(real[])
```

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Fixes #446 by adding the following signatures:

```
vector reverse(vector)
row_vector reverse(row_vector)
int[] reverse(int[])
real[] reverse(real[])
vector[] reverse(vector[])
row_vector[] reverse(row_vector[])
matrix[] reverse(matrix[])
int[,] reverse(int[,])
real[,] reverse(real[,])
vector[,] reverse(vector[,])
row_vector[,] reverse(row_vector[,])
matrix[,] reverse(matrix[,])
int[,,] reverse(int[,,])
real[,,] reverse(real[,,])
vector[,,] reverse(vector[,,])
row_vector[,,] reverse(row_vector[,,])
matrix[,,] reverse(matrix[,,])
int[,,,] reverse(int[,,,])
real[,,,] reverse(real[,,,])
vector[,,,] reverse(vector[,,,])
row_vector[,,,] reverse(row_vector[,,,])
matrix[,,,] reverse(matrix[,,,])
int[,,,,] reverse(int[,,,,])
real[,,,,] reverse(real[,,,,])
vector[,,,,] reverse(vector[,,,,])
row_vector[,,,,] reverse(row_vector[,,,,])
matrix[,,,,] reverse(matrix[,,,,])
int[,,,,,] reverse(int[,,,,,])
real[,,,,,] reverse(real[,,,,,])
vector[,,,,,] reverse(vector[,,,,,])
row_vector[,,,,,] reverse(row_vector[,,,,,])
matrix[,,,,,] reverse(matrix[,,,,,])
int[,,,,,,] reverse(int[,,,,,,])
real[,,,,,,] reverse(real[,,,,,,])
vector[,,,,,,] reverse(vector[,,,,,,])
row_vector[,,,,,,] reverse(row_vector[,,,,,,])
matrix[,,,,,,] reverse(matrix[,,,,,,])
```

so basically all types are accepted except for reverse(int) and reverse(real) and reverse(matrix).

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@mcol please double check if this is what you meant. Math compiles for all of the above.

**Comment by mcol** [comment]
I always thought that `reverse()` would only apply to vector-like types, so I'm not sure what it would mean to reverse a matrix: I suppose it would reverse each column, but I'm not sure it would be useful (I also didn't write tests for that use case in math). So I would leave out the matrix types and keep the rest.

**Comment by rok-cesnovar** [comment]
Not sure I understand.

Lets say we have a vector {a, b, c}, reverse({a,b,c}) will return {c,b,a} but the a,b, and c elements themselves are not reversed. We discussed this in Math. 

So is there a difference if a, b and c are int,, reals, vector, row_vectors or matrices? I would say no. However, if its not tested in Math, it should not be added in.

So if I understand correctly, it should be:

```
vector reverse(vector)
row_vector reverse(row_vector)
int[] reverse(int[])
real[] reverse(real[])
vector[] reverse(vector[])
row_vector[] reverse(row_vector[])
int[,] reverse(int[,])
real[,] reverse(real[,])
vector[,] reverse(vector[,])
row_vector[,] reverse(row_vector[,])
int[,,] reverse(int[,,])
real[,,] reverse(real[,,])
vector[,,] reverse(vector[,,])
row_vector[,,] reverse(row_vector[,,])
matrix[,,] reverse(matrix[,,])
int[,,,] reverse(int[,,,])
real[,,,] reverse(real[,,,])
vector[,,,] reverse(vector[,,,])
row_vector[,,,] reverse(row_vector[,,,])
int[,,,,] reverse(int[,,,,])
real[,,,,] reverse(real[,,,,])
vector[,,,,] reverse(vector[,,,,])
row_vector[,,,,] reverse(row_vector[,,,,])
int[,,,,,] reverse(int[,,,,,])
real[,,,,,] reverse(real[,,,,,])
vector[,,,,,] reverse(vector[,,,,,])
row_vector[,,,,,] reverse(row_vector[,,,,,])
int[,,,,,,] reverse(int[,,,,,,])
real[,,,,,,] reverse(real[,,,,,,])
vector[,,,,,,] reverse(vector[,,,,,,])
row_vector[,,,,,,] reverse(row_vector[,,,,,,])
```

**Comment by mcol** [comment]
Sorry, the syntax got me confused, I must have imagined a `matrix reverse(matrix)`. The updated list is fine, but note that you still have `matrix[,,] reverse(matrix[,,])`.

**Comment by rok-cesnovar** [comment]
The logic
```ocaml
  for i = 0 to 7 do
    add_unqualified ("reverse", (ReturnType (bare_array_type (UVector, i))), [bare_array_type (UVector, i)]) ;
    add_unqualified ("reverse", (ReturnType (bare_array_type (URowVector, i))), [bare_array_type (URowVector, i)]) ;
  done ;
  for i = 1 to 7 do
    add_unqualified ("reverse", (ReturnType (bare_array_type (UInt, i))), [bare_array_type (UInt, i)]) ;
    add_unqualified ("reverse", (ReturnType (bare_array_type (UReal, i))), [bare_array_type (UReal, i)]) ;
    add_unqualified ("reverse", (ReturnType (bare_array_type (UMatrix, i))), [bare_array_type (UMatrix, i)])
  done ;  
```
basically says for vector and row vector add array of zero to 7 dimensions.
For int, real and matrix add array of 1 to 7 dimensions. 
> but note that you still have `matrix[,,] reverse(matrix[,,])`

copy paste error.

Ok will remove matrices, then its ready.

**Comment by rok-cesnovar** [comment]
Done, updated top-level comment. Ready for review.

**Comment by bob-carpenter** [comment]
The complete set of signatures should be

```
vector reverse(vector x);
row_vector reverse(row_vector x);
T[] reverse(T[] x)
```

where `T` is any Stan type.  

For example, the case of `T = matrix[ , ]` leads to `matrix[ , , ] reverse(matrix[ , , ])` and is fine.

**Comment by rok-cesnovar** [comment]
That was the original version here yeah. Will put that back.

**Comment by rok-cesnovar** [comment]
> The complete set of signatures should be
> 
> ```
> vector reverse(vector x);
> row_vector reverse(row_vector x);
> T[] reverse(T[] x)
> ```

I reverted back to this and also updated the top-level comment. Ready for review.

**Comment by rok-cesnovar** [comment]
Thanks @rybern

**Pull request merged**
