### PR TITLE
Add *_constrain and *_free functions from Stan Math

### PR DESCRIPTION
**Pull request by nhuurre**
Closes issue #307 because identifiers that shadow these will now cause the compiler to fail early with a clear error message.

The old Stan compiler did not expose these functions and in fact allowed their names to be used in a model without conflicts. While it would have been possible to recover the old behaviour I believe that exposing the functions is more reasonable.

Known bugs:
* `cholesky_corr_free` and `corr_matrix_free` are not autodiffable.
* If the first argument to `lub_constrain` is of type `int` then C++ compiler deduces a bad template specialization and the function will return nonsense.

Copyright holder: Niko Huurre

By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:

* Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
* Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

### CODE REVIEW

**Comment by seantalts** [comment]
Let me get these tests working again, sorry!

**Comment by seantalts** [comment]
Hmm, this is not obvious though - do we actually want to expose these? @bob-carpenter what do you think? I could see it going either way, but if we were going to expose them we'd need to add all the doc to the manual as well. The names are a bit suboptimal too.

The other option I can think of is to appropriately namespace them in the compiled code - e.g. prepend `stan::math::` to their names.

**Comment by seantalts** [comment]
In the absence of @bob-carpenter response, would you mind if we closed this for now and just namespaced these function calls instead for the time being? I'm not sure we want to go through with adding that many functions to the language all at once just to solve this bug in time for the release.

**Comment by nhuurre** [comment]
No problem.

**Pull request closed without merging**
