### PR TITLE
Compatibility with OCaml 4.12.0

### PR DESCRIPTION
**Pull request by mandel**
## Release notes

Update the code of the compiler to make it compatible with:
- OCaml 4.12.0
- dune 2.8.2
- core_kernel v0.14.1 
- menhir 20201216 
- ppx_deriving 5.2.1
- fmt 0.8.9
- yojson 1.7.0

These changes are compatible with the current requirements.

Upgrading to `ocamlformat 0.17.0` changes the formatting of the code and thus is not retro-compatible with `ocamlformat 0.8`.

This PR is useful for issues  #779 and #710. 

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Thanks!!

Also helpful for https://github.com/stan-dev/stanc3/pull/627

Will push the relevant CI changes if others are good with this @seantalts @rybern @nhuurre

**Comment by rok-cesnovar** [comment]
We will very likely have to remain at 4.11 until ocaml-cross-windows is updated (that is required for building Windows binaries).

**Comment by mandel** [comment]
I still have not identified the problem, but it seems that it is in `Optimize.lazy_code_motion`.

**Comment by SteveBronder** [comment]
I had some time to look at this today and I think the issue is that a lot of the stuff in the optimizer uses if's and && and || and those are causing some weird bad things to happen in the ocaml

**Comment by rok-cesnovar** [comment]
I am not sure we will be able to make it work with 4.12.0 due to https://github.com/ocaml-cross/opam-cross-windows that we use to make windows executables. They state that the latest supported version is 4.11.1

**Comment by SteveBronder** [comment]
I have a branch of this that sort of works for 4.11.1 @mandel if you can take a look. 

What I can't figure out is why we need to import `=` from stdlib now? Is there something we need to change with how we import stuff? Feels counterintuitive to have to import the equality operators

https://github.com/stan-dev/stanc3/compare/master...SteveBronder:update/4.11.1?expand=1

**Comment by mandel** [comment]
Sorry for the late answer!

We have to import the comparison operators now due to a change in the Core library. They are masking the polymorphic equality  of the standard library (https://discuss.ocaml.org/t/removing-polymorphic-compare-from-core/2994). So to recover it, we have to re-import it after importing Core.

@SteveBronder Your branch looks good to me! The only thing that I do not understand is why you have to do the `open Stdlib` in `Ast.ml`. How do you want to proceed? Do you want to commit your changes in this branch or do a new PR?

**Comment by mandel** [comment]
@SteveBronder Sure you can merge here!

**Comment by mandel** [comment]
> icic okay so your code makes sense now. I'm looking at this thread and it just seems odd that ocaml doesn't allow you to have your own overloaded comparison operators defined for a given type, but whatever. imo I'd prefer we just write equals functions for each of our types instead of importing the polymorphic one from stdlib. But if that's a lot of hassle then I'm fine with just have the polymorphic import.

I agree that it can be nice to use type specific equals but it is a big amount of work. I though that it can be done in multiple stages. First have the code working with the polymorphic equal (like the 4.07 version). Then switch the equals.

**Comment by mandel** [comment]
I renamed the branch https://github.com/mandel/stanc3/tree/update-4.12

**Comment by mandel** [comment]
The development of this is now in https://github.com/stan-dev/stanc3/pull/885

**Pull request closed without merging**
