### PR TITLE
Multiarch Stanc3 Building

### PR DESCRIPTION
**Pull request by andrjohns**
## Summary

This PR adds automatic building of Stanc3 for multiple linux architectures:

  - `arm64`
  - `armhf`
  - `armel`
  - `mips64el`
  - `ppc64el`
  - `s390x`

This is done using Docker images that are run through QEMU and don't require separate instances for each architecture. The base Dockerfile and instructions for building on each architecture are also included

## Release notes

Adds build process for arm64, armhf, armel, mips64el, ppc64el and s390x linux architectures

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by serban-nicusor-toptal** [comment]
Hey @andrjohns what was the issue ? Was it a Jenkins bug for that old PR ?

**Comment by andrjohns** [comment]
At some point I'd run `chown opam: $(pwd)` in the Jenkinsfile, so the gitconfig ownership/permissions were messed up for the rest of the PR. Rookie mistake!

**Comment by rok-cesnovar** [comment]
Thanks for working on this Andrew. It would be great if we could build the ARM binary with docker, would remove the need for the ARM instance.

**Comment by serban-nicusor-toptal** [comment]
Nice, congrats on finding it!

**Comment by andrjohns** [comment]
No worries! I've got an initial approach working at the moment (current state of PR), but it's a bit round-about and inefficient. The next step is using docker images directly for the target architecture (rather than chrooting inside an x86 image), which should be much simpler. Looking promising!

**Comment by andrjohns** [comment]
All binaries are now building and tests passing, hooray! The docker images for building are currently hosted on docker hub under my name, should we instead setup a dedicated 'stan-dev' account?

**Comment by serban-nicusor-toptal** [comment]
Hey, I can set that up for you right now. I will edit my post with the results.

**Comment by andrjohns** [comment]
Hmm sounds tricky. Might be best to leave it pulling from mine for now, and then we can update later. I've included build instructions with the dockerfile, so it will be easy to update later.

This is now ready for review. I'll update the top-level description, and I think the commits should be squashed before merging

**Review by rok-cesnovar — APPROVED** [review]
This looks great to me. Sorry for the delay Andrew, was mostly away for a few weeks.

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal you can now remove the ARM instance, there is no need for it anymore.

**Comment by serban-nicusor-toptal** [comment]
@rok-cesnovar Done!

**Comment by andrjohns** [comment]
No worries at all, thanks Rok!

**Pull request merged**
