### PR TITLE
Allow complex promotion in functions, not just operators

### PR DESCRIPTION
**Pull request by WardBrian**
This address the first portion of #998. We still need to do static casting in the code generation so the C++ will compile.

Currently, things like 

```stan
    complex foo_two(complex z, complex z2){
      return add(z,z2);
    }
   
    foo_two(1, 3.5);
```

throw signature errors because we're not properly allowing promotion for functions.

Partially this was caused by the fact that we have different systems for checking functions and checking operators, but this does not fix that issue, just repair this symptom for now.

However, this now fails at C++ time. 

So does something like `proj(1.0)`.

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [x] OR, no user-facing changes were made

## Release notes

Fixed an issue with calling functions that expect complex arguments with reals or integers.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by SteveBronder** [comment]
Will do! Trying to finish up some of the adjoint ODE fix today then I will look at this

**Comment by SteveBronder** [comment]
>> Also I just realized idt we can generate functions that take in an array of array of complex types?

> Why not?

How do you write the signature? I think the C++ always gens `const std::vector<std::complex<T1__>>&` no? Maybe I just don't know the syntax

I'll take a stab at the compiler internal promotion type tmrw. That feels like the cleanest way imo

**Comment by WardBrian** [comment]
Does `void foo(array[,,] complex zs){...}` not codegen at the moment? That sounds like a whole other kind of issue if so

**Comment by SteveBronder** [comment]
Oh whoops nvm!

**Comment by SteveBronder** [comment]
The backend for this is pretty much the same whether I do the big or small thing so I'm just going to the full promotion thing

**Comment by WardBrian** [comment]
Array literal promotion for complex works in Stan, I’ll need to check that the C++ compiles and that we have it in the test

**Comment by WardBrian** [comment]
Superceded by #1004

**Pull request closed without merging**
