### PR TITLE
Bugfix/issue 516 MPI map_rect fix

### LINKED ISSUE #516: MPI map_rect doesnt register all functor
The credit for finding this one goes to @nhuurre.

In the case of 
```
  vector[3] y_hat_gq
      = map_rect(foo, shared_params_d, job_params_d, data_r, data_i)
        + map_rect(goo, shared_params_d, job_params_d, data_r, data_i);
```
the second call will not add a `STAN_REGISTER_MAP_RECT` call and will also cause issues all around.

With this example model
[mpi_map_rect.stan.txt](https://github.com/stan-dev/stanc3/files/4473785/mpi_map_rect.stan.txt)
stanc3 produces 
[mpi_map_rect.hpp.txt](https://github.com/stan-dev/stanc3/files/4473807/mpi_map_rect.hpp.txt)

grep "map_rect<"  on the generated hpp returns
```cpp
        map_rect<1, foo_functor__>(shared_params_p, job_params_d, data_r,
        map_rect<2, foo_functor__>(shared_params_d, job_params_p, data_r,
        map_rect<3, foo_functor__>(shared_params_p, job_params_d, data_r,
        map_rect<4, foo_functor__>(shared_params_p, job_params_d, data_r,
        map_rect<5, foo_functor__>(shared_params_d, job_params_p, data_r,
        map_rect<6, foo_functor__>(shared_params_p, job_params_d, data_r,
          map_rect<7, foo_functor__>(shared_params_d, job_params_d, data_r,
          map_rect<8, goo_functor__>(shared_params_d, job_params_d, data_r,
        map_rect<9, goo_functor__>(shared_params_d, job_params_d, data_r,
```
but we see this:
```
STAN_REGISTER_MAP_RECT(1, mpi_model_namespace::goo_functor__)
STAN_REGISTER_MAP_RECT(2, mpi_model_namespace::foo_functor__)
STAN_REGISTER_MAP_RECT(3, mpi_model_namespace::foo_functor__)
STAN_REGISTER_MAP_RECT(4, mpi_model_namespace::foo_functor__)
STAN_REGISTER_MAP_RECT(5, mpi_model_namespace::foo_functor__)
STAN_REGISTER_MAP_RECT(6, mpi_model_namespace::foo_functor__)
STAN_REGISTER_MAP_RECT(7, mpi_model_namespace::foo_functor__)
```
which is wrong obviously. 

This is only an issue with MPI map_rect when map_rect is used in the second argument of another function. Not sure if that is a common case for map_rect but a fix is incoming in a minute.

### PR DESCRIPTION
**Pull request by rok-cesnovar**
- update motherHOF.stan to include the problematic case
- remove what was termed "code smell" (a ref variable used as a counter of map_rect calls)
- fixes #516

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This is ready for review and something some users have noticed. 

Since its easy to use a nightly build of stanc3 with cmdstan (rm bin/linux-stanc bin/mac-stanc and make build is all you need) this would be great to get fixed asap.

**Comment by wds15** [comment]
Any idea why this bug was not caught by our testing machinery? This is what confuses me a bit. I mean, the cmdstan repo test should have caught this, no?

**Comment by rok-cesnovar** [comment]
The problem is that the stanc3 test model did not have a test that would catch this, just basic use of map_rect that is stored directly in a variable. 

This problem was carried over from the previous Stanc2 test model: https://github.com/stan-dev/stan/blob/1bb054027b01326e66ec610e95ef9b2a60aa6bec/src/test/test-models/good/map_rect.stan

So just a lack of test coverage for this case. 

Cmdstan has no tests with map_rect models. Well,  cmdstan actually only has interface tests that are not designed to catch these types of things. These should be caught by the stanc3/stan tests.

**Comment by wds15** [comment]
Oh... shame on me.. but you got that covered for the future if I get you right. 

+1

**Comment by rok-cesnovar** [comment]
I am not blaming anyone :) Test coverage is tricky business and in my opinion never one man's job.

> but you got that covered for the future if I get you right.

See the last changed file in: https://github.com/stan-dev/stanc3/pull/517/files

I am going to add the example from Richard McElreath's tutorial as well.

**Pull request merged**
