### PR TITLE
[Early WIP]: var_value<Eigen::matrix>

### PR DESCRIPTION
**Pull request by rok-cesnovar**
PR to discuss progress on varmat (see #668) stanc3 support.

Right now this is a prototype where any variable with _varmat is declared as `var_value<Eigen::matrix>`

## Release notes

/

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Binaries at https://github.com/stan-dev/stanc3/actions/runs/396985407

**Comment by bbbales2** [comment]
Compiling the model `mrp_varmat.stan` here: https://github.com/bbbales2/computations_in_glms/tree/master/benchmark_model

I'm getting errors in the random effects part of:
```
  vector[N] mu_varmat = Intercept + Xc * b_varmat
    + r_age_varmat[J_age]
    + r_educ_varmat[J_educ]
    + r_educ_age_varmat[J_educ_age]
    + r_educ_eth_varmat[J_educ_eth]
    + r_eth_varmat[J_eth]
    + r_male_eth_varmat[J_male_eth]
    + r_state_varmat[J_state];
```

That's everything `r_age_varmat[J_age]` and onwards. I can remove these terms and the model compiles and runs and produces results that mix with the non-varmat model.

The errors are at C++ compile and go like this:

```
--- Compiling, linking C++ code ---
clang++ -std=c++1y -D_REENTRANT -Wno-sign-compare -Wno-ignored-attributes      -I stan/lib/stan_math/lib/tbb_2019_U8/include   -O3 -I src -I stan/src -I lib/rapidjson_1.1.0/ -I stan/lib/stan_math/ -I stan/lib/stan_math/lib/eigen_3.3.7 -I stan/lib/stan_math/lib/boost_1.72.0 -I stan/lib/stan_math/lib/sundials_5.2.0/include    -DBOOST_DISABLE_ASSERTS        -c -include-pch stan/src/stan/model/model_header.hpp.gch -x c++ -o mrp_varmat.o mrp_varmat.hpp
mrp_varmat.hpp:850:25: error: no matching function for call to 'rvalue'
                        rvalue(r_age_varmat,
                        ^~~~~~
mrp_varmat.hpp:1741:14: note: in instantiation of function template specialization
      'mrp_varmat_model_namespace::mrp_varmat_model::log_prob<false, false, stan::math::var_value<double, void> >' requested here
      return log_prob<propto__,jacobian__,T_>(vec_params_r, vec_params_i, pstream);
             ^
/home/bbales2/cmdstan-develop/stan/src/stan/model/model_base_crtp.hpp:95:50: note: in instantiation of function template specialization
      'mrp_varmat_model_namespace::mrp_varmat_model::log_prob<false, false, stan::math::var_value<double, void> >' requested here
    return static_cast<const M*>(this)->template log_prob<false, false>(theta,
                                                 ^
mrp_varmat.hpp:202:3: note: in instantiation of member function 'stan::model::model_base_crtp<mrp_varmat_model_namespace::mrp_varmat_model>::log_prob' requested here
  ~mrp_varmat_model() final { }
  ^
/home/bbales2/cmdstan-develop/stan/src/stan/model/indexing/rvalue.hpp:54:10: note: candidate function not viable: no known conversion from
      'stan::model::cons_index_list<stan::model::index_multi, stan::model::nil_index_list>' to 'const stan::model::nil_index_list' for 2nd argument
inline T rvalue(T&& x, const nil_index_list& /*idx*/, const char* /*name*/ = "",
         ^
/home/bbales2/cmdstan-develop/stan/src/stan/model/indexing/rvalue.hpp:73:10: note: candidate function not viable: no known conversion from
      'cons_index_list<stan::model::index_multi, [...]>' to 'const cons_index_list<stan::model::index_omni, [...]>' for 2nd argument
inline T rvalue(T&& x, const cons_index_list<index_omni, nil_index_list>& idxs,
         ^
/home/bbales2/cmdstan-develop/stan/src/stan/model/indexing/rvalue.hpp:111:10: note: candidate function not viable: no known conversion from 'cons_index_list<stan::model::index_multi,
      stan::model::nil_index_list>' to 'const cons_index_list<stan::model::index_omni, cons_index_list<stan::model::index_omni, stan::model::nil_index_list>>' for 2nd argument
inline T rvalue(
         ^
/home/bbales2/cmdstan-develop/stan/src/stan/model/indexing/rvalue.hpp:92:13: note: candidate template ignored: requirement '!is_same<var_value<Matrix<double, -1, 1, 0, -1, 1>, void>,
      var_value<Matrix<double, -1, 1, 0, -1, 1>, void> >::value' was not satisfied [with T = stan::math::var_value<Eigen::Matrix<double, -1, 1, 0, -1, 1>, void> &]
inline auto rvalue(T&& x,
            ^
```

**Comment by SteveBronder** [comment]
I got this working on a local branch (I whoops'd a header include in the test branch that aggregates all the indexing stuff together). I'll make a cmdstan branch that has all this stuff. Rok is there a way to point cmdstan to a particular binary build?

**Comment by SteveBronder** [comment]
Good news though! For the `var<mat>` version I'm seeing with `mrp_all.json`

```
Gradient evaluation took 0.009705 seconds
1000 transitions using 10 leapfrog steps per transition would take 97.05 seconds.
Adjust your expectations accordingly!
```

and for the mat<var> version we have 

```
Gradient evaluation took 0.019417 seconds
1000 transitions using 10 leapfrog steps per transition would take 194.17 seconds.
Adjust your expectations accordingly!
```

So about twice as fast!

**Comment by rok-cesnovar** [comment]
We currently do not have a one-click way of sharing these Github Actions binaries as they show up as .zip archives.

If you have a publicly accessible URL, then you can put them in a bin folder and set
`STANC3_TEST_BIN_URL = https://someurl.com/subfolder`
and if the binaries are at https://someurl.com/subfolder/bin/linux-stanc etc. this would be enough.

For now, I made a pre-release on my fork and you can just simply do what I did here: https://github.com/stan-dev/cmdstan/commit/8413847c768547784f3ca6b59b094bb93bb3aaf2

I think this is simple enough and I will just replace the binaries there as we progress further with this.

**Comment by bbbales2** [comment]
Is the working stan branch uploaded anywhere?

@rok-cesnovar how far along is your timing thing? I am curious how much time we are spending in likelihood vs prior in these two models.

**Comment by rok-cesnovar** [comment]
> how far along is your timing thing?

Should get it back running this week barring any huge surprises.

**Comment by bbbales2** [comment]
I'm copy-pasting this from the Google doc so it's on Github. It is Rok's list of different options for the compiler. Feel free to move this text elsewhere.

```
a) A new Stan type for varmat

Pros:
+ better control over when to use varmat
Cons:
- a lot of documentation to explain the difference to the user
- harder for support questions (users will need to understand AD more than usually)
- longer list of signatures, what about mixing matvar and varmat?

b) only use varmat if everything in the model supports varmat and there is no single cell indexing in model/TP

Pros:
- easy to use as long as the user knows the limitations
- No need for user-facing docs
Cons:
- support issues: users adds single cell indexing and the model becomes A LOT slower (knowing the limitations is hard)

c) more advanced logic in stanc3 for when to use varmat

Pros:
- mostly seamless to the user
- No need for user facing docs
Cons:
- really complex stanc3 implementation

d) Generate only varmat code in Stanc3

Pros:
- Easiest to implement in the compiler
- User facing docs simple -- prefer vectorization over loops
Cons:
- Scalar indexing of a varmat is currently expected to be slower than a matvar
- Need to guarantee that all the matrix functions work with varmat. That means adding reverse mode implementations of a lot of functions which currently don’t have them
```

**Pull request closed without merging**
