### PR TITLE
Add linspaced_int_array()

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Release notes

Added `linspaced_int_array()`

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@bbbales2 mind reviewing this? Its simple. 

I checked that the new sig  compiles. There is no expressions here so no fear of any hidden stuff there.

**Review by bbbales2 — COMMENTED** [review]
Looks good to me but the test failed?

**Comment by rok-cesnovar** [comment]
Forgot to format Ocaml.

**Comment by rok-cesnovar** [comment]
Docs PR also open https://github.com/stan-dev/docs/pull/312

**Review by bbbales2 — APPROVED** [review]
Good

**Pull request merged**
