### PR TITLE
Fix building Windows binary

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Trying to fix building Windows binary

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@serban-nicusor-toptal can you install dos2unix in the WSL and update the image? Or if easier install 4. and on from https://github.com/stan-dev/stanc3/tree/master/scripts in the Linux machines?

**Comment by serban-nicusor-toptal** [comment]
Hey, already working on getting the Linux machine ready for this, hope to have all ready around tomorrow! I didn't create a GitHub issue mb.

**Comment by rok-cesnovar** [comment]
Oh, cool! Going to close this then. Thanks! Let me know if I can help with anything.

**Comment by serban-nicusor-toptal** [comment]
Hey,

I am trying to setup the linux machines but been stuck for a while on
something ...
Following this
https://github.com/stan-dev/stanc3/blob/master/scripts/README.MD
+
https://github.com/stan-dev/stanc3/blob/fab03be2cd496dd026a5cd0de920e4ef84f36cf3/scripts/install_build_deps.sh#L5
to get around the octavius-windows package error

I saw an old issue here https://github.com/ocaml/dune/issues/2219
and I've tried to downgrade but I still get the following:

opam 2.0.2
dune 1.11.4

ubuntu@ip-172-31-1-228:/tmp/stanc3$ dune build -x windows
File "dune-project", line 1, characters 11-14:
1 | (lang dune 2.0)
               ^^^
Error: Version 2.0 of dune is not supported.
Supported versions:
- 0.0
- 1.0 to 1.11

Any idea what may be wrong? That error message is a bit misleading

Thanks!

**Comment by rok-cesnovar** [comment]
Dont the linux machines already run ocaml and thus have 
https://github.com/stan-dev/stanc3/blob/fab03be2cd496dd026a5cd0de920e4ef84f36cf3/scripts/install_build_deps.sh#L5

If you first setup native Linux developmen and then try to 

```
sudo add-apt-repository ppa:avsm/ppa
sudo apt-get update
sudo apt-get install opam mingw-w64 gcc m4 make -y
opam repository add windows git://github.com/ocaml-cross/opam-cross-windows
opam install conf-flambda-windows
opam install "ocaml-windows64<=4.07.0"
opam install -y core_kernel-windows menhir-windows ppx_deriving-windows fmt-windows
sudo apt-get install dos2unix
```

**Comment by serban-nicusor-toptal** [comment]
This runs in docker on linux, the machine didn't have it.
It looks like there was a problem with the versions, it needs specifically `dune 1.11.3`,`opam 2.0.4` or else it either doesn't work or throw infinite warnings and errors.
Gonna wait for the image to build, switch it and test to see if everything works properly

**Pull request closed without merging**
