### PR TITLE
fix indexing in transform_init

### PR DESCRIPTION
**Pull request by nhuurre**
I think this should fix issue #609

Pretty sure indexing in `unconstrained_param_names()` is also broken but [a comment](https://github.com/stan-dev/stanc3/blob/5de57e01f7e070b745696307aacfe229d4774958/src/stan_math_backend/Stan_math_code_gen.ml#L505-L507) says it's probably always been broken in other ways too.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
Model

```stan
parameters {
  matrix[1,2] p_ar_mat[3];
}
model {
    for (i in 1:3)
      for (k in 1:1)
        for (l in 1:2)
          p_ar_mat[i, k, l] ~ normal(0,1);
}
generated quantities {
  matrix[1,2] gq_ar_mat[3];
      for (i in 1:3)
        for (k in 1:1)
          for (l in 1:2)
            gq_ar_mat[i, k, l] = p_ar_mat[i, k, l];
}
```

fails with sampling with this fix.

**Comment by nhuurre** [comment]
> fails with sampling with this fix.
Does sampling even use `transform_inits`? Oh, right `gen_write` is used for other stuff too. Oops.

**Comment by rok-cesnovar** [comment]
> Does sampling even use `transform_inits`?

No, sampling does not use it. Otherwise, we would see this one earlier.

**Comment by nhuurre** [comment]
Ok, how about now?

**Comment by rok-cesnovar** [comment]
Sampling is fine now, but the generate_quantities fails with:

`Exception: matrix[uni,uni] indexing, row: accessing element out of range. index 2 out of range; expecting index to be between 1 and 1 (in 'examples/bugs/tgq.stan', line 2, column 2 to column 26)`

What I run is:

`./examples/bugs/tgq sample output file=fit.csv`
and then just
`./examples/bugs/tgq sample output file=fit.csv`

**Pull request merged**
