### PR TITLE
Cleanup tests of deprecated functions

### PR DESCRIPTION
**Pull request by rok-cesnovar**
## Release notes

Cleaned up distribution tests of deprecated _log functions.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
This is required for https://github.com/stan-dev/stanc3/issues/600 because these distribution test files would generate a few 100k deprecation warnings.

**Comment by seantalts** [comment]
Did you run a script for this? Could you paste the script somewhere? Seems easier than reviewing the 800,000 lines of changes :D

**Comment by rok-cesnovar** [comment]
I ran it with regex in Visual Studio code (first for continuous (lpdf) and discrete(lpmf). I can re-do this with a script if that would make it easier, not a problem. This is easy.

Otherwise, all the changes are inside the `test/integration/good/function-signatures/distributions/`: *.stan files and pretty.expected files.

I think the easiest check would be that there is no error in `test/integration/good/function-signatures/distributions/.*/pretty.expected`.

There is a catch though. There is one error in a pretty.expected file now. And it's legit:
https://github.com/stan-dev/stanc3/blob/master/src/middle/Stan_math_signatures.ml#L1509 and
https://github.com/stan-dev/stanc3/blob/master/src/middle/Stan_math_signatures.ml#L1517

should represent the same signature I suppose (given that in _log calls the _lpmf) version.
I didn't want to fix that here as no one can spot that. I also have to double-check which signatures actually work and are listed in docs.

**Comment by rok-cesnovar** [comment]
Will re-do with a script. I realized this is impossible to review.

**Comment by rok-cesnovar** [comment]
Also not sure why I didn't just use print-canonical... doh

There is no useful or necessary comments in these files.

**Pull request closed without merging**
