### PR TITLE
Add a transformed_mir_diff expect test for #856 to diff against

### PR DESCRIPTION
**Pull request by seantalts**
Just adding an expect test so we can track changes in the transformed MIR as well as the pre-transform MIR.

(no release notes)

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Review by rok-cesnovar — APPROVED** [review]
Thanks Sean!

**Comment by seantalts** [comment]
@rok-cesnovar while you're here, what do you think of this idea of adding the transformed MIR expect test as a diff from the pre-transform one? Is that too complicated? That's what's currently up - it's about 15000 lines as a diff, and about 30,000 lines not as a diff. Also, the diff logic uses bash so may not be portable - waiting for Jenkins to yell. I have the non-diff version ready to push if it doesn't work or you like the non-diff version better. I get a little confused thinking about future PRs comparing a diff of a diff...

**Comment by rok-cesnovar** [comment]
Honestly, 30k is not that big and it makes is simpler to understand I guess? There are a bunch of distributions with 35k+ expected lines and those are not nearly as important as this.

**Comment by seantalts** [comment]
Sounds good. Also, apparently `diff` has different behavior on mac, lol. Pushing up the simpler version, thank you!

**Pull request merged**
