### PR TITLE
Add sum_to_zero transform

### PR DESCRIPTION
**Pull request by WardBrian**
~Draft because it relies on https://github.com/stan-dev/stan/pull/3308 and one of https://github.com/stan-dev/math/pull/3099 https://github.com/stan-dev/math/pull/3101~

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: TBD
  
## Release notes

Added the `sum_to_zero` transform for vector types.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by nhuurre** [comment]
The original issue asks for `zero_sum_vector` but here it has been renamed to `sum_to_zero`. I didn't see any discussion as to why. Personally, I prefer `zero_sum` (without `_vector`, cf. `ordered`)

**Comment by WardBrian** [comment]
@bob-carpenter listed these for consideration in an email with me before implementation work began


* zero_sum
* zero_sum_vector
* sum_to_zero
* sum_to_zero_vector

I don't have that strong of a preference, but I do think sum_to_zero is more self explanatory without being that much longer

**Comment by WardBrian** [comment]
`sum_to_zero_vector` is shorter than some of the other types (I think `cholesky_factor_corr` holds that title?), so if that sounds better to others I'm happy to make the change

**Review by SteveBronder — APPROVED** [review]
Good!

**Pull request merged**
