### PR TITLE
[WIP] Variadic ODE

### PR DESCRIPTION
**Pull request by rok-cesnovar**
Opened to fix https://github.com/stan-dev/stanc3/issues/481

For now this is opened so we can discuss any implementation issues for this experimental phase.
This is basically done the same way as the reduce_sum.

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
@bbbales2 cmdstan branch https://github.com/stan-dev/cmdstan/tree/variadic_ode has everything you need to compiled and run the example you posted on the issue. As for the reduce_sum, this does no checks.

I am running the model now.

**Comment by bbbales2** [comment]
@rok-cesnovar Amazing!!! Thank you!

@wds15 so you know

**Comment by bbbales2** [comment]
@rok-cesnovar I used this and it works great!

It looks like there's a problem using the old signatures.

The old functors used to look like:
```
struct harm_osc_ode_data_fun {
  template <typename T0, typename T1, typename T2>
  inline std::vector<typename stan::return_type<T1, T2>::type>                                                                                                                                                                                         
  operator()(const T0& t_in, const std::vector<T1>& y_in,
             const std::vector<T2>& theta, const std::vector<double>& x,
             const std::vector<int>& x_int, std::ostream* msgs){
  ...
  }
}
```

The new interface expects functors to look like:
```
struct harm_osc_ode_data_fun {
  template <typename T0, typename T1, typename T2, typename T3, typename T4>
  inline std::vector<typename stan::return_type<T1, T2, T3, T4>::type>
    operator()(const T0& t_in, const std::vector<T1>& y_in,
             const std::vector<T2>& theta, const std::vector<T3>& x,
             const std::vector<T4>& x_int, std::ostream* msgs){
  ...
  }
}
```

So they have extra template arguments.

When generating code from the new code generator for the new function calls the code (correctly) looks like:
```
struct dz_dt_obfunctor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__,
typename T4__, typename T5__>
std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__, T3__,
T4__, typename boost::math::tools::promote_args<T5__>::type>::type>
operator()(const T0__& t, const std::vector<T1__>& z, const T2__& alpha,
           const T3__& beta, const T4__& gamma, const T5__& delta,
           std::ostream* pstream__)  const
{
return dz_dt(t, z, alpha, beta, gamma, delta, pstream__);
}
};
```

When generating code with the new code generator for the old ODE functions the code looks like:
```
struct dz_dt_functor__ {
template <typename T0__, typename T1__, typename T2__, typename T3__>
std::vector<typename boost::math::tools::promote_args<T0__, T1__, T2__,
T3__>::type>
operator()(const T0__& t, const std::vector<T1__>& z,
           const std::vector<T2__>& theta, const std::vector<T3__>& x_r,
           const std::vector<int>& x_i, std::ostream* pstream__)  const
{
return dz_dt(t, z, theta, x_r, x_i, pstream__);
}
};
```

But for things to compile that 'int' for x_i needs to be a template argument.

I missed this in the last commit I made to the math library cause I didn't check the integrate_ode_* functions. I'll need to do something about those tests.

I think the long and short of it is we have a ton of things that expect functions as arguments. We should probably push to standardize these things somehow, but maybe that isn't convenient.

**Comment by rok-cesnovar** [comment]
@bbbales2 I tried to compile the old model on master and on this branch and both work fine. On this branch both `dz_dt_obfunctor__` and `dz_dt_functor__` are generated. Maybe I am missing your point here.

The latest binaries will be available soon here: https://jenkins.mc-stan.org/job/stanc3-test-binaries/33/

**Comment by rok-cesnovar** [comment]
I am going to close this and reopen once I have time to do things the way they are now done on the reduce sum PR.

**Pull request closed without merging**
