### PR TITLE
[WIP] Composable transforms

### PR DESCRIPTION
**Pull request by WardBrian**
## Overview
This PR refactors our internal representation of transformations to include a concept of 'chaining' several in a row. The idea is roughly based on [TFP's Chain bijector](https://www.tensorflow.org/probability/api_docs/python/tfp/bijectors/Chain). 

The code generation is based on turning something which currently would be codgen'd as
```c++
      y = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,  lp__);
```
into
```c++
      y = lb_constrain<jacobian__>(in__.template read<local_scalar_t__>(),
                                                     0, lp);
```
with the obvious extension that you can add additional reassignments to add additional constraints, e.g.
```c++
      y = lb_constrain<jacobian__>(
              offset_multiplier_constrain<jacobian__>(
                   in__.template read<local_scalar_t__>(), 1, 3, lp__),
              0, lp__);
```

The same is done (in reverse order) for freeing.

There are several areas of the code which are not yet completed (hence the WIP). They are all marked with the string "TR TODO" in either a comment or a failwith statement.

-----
## Remaining work here
- [x] Variables with transforms can also be 'checked' that they are properly constrained. The way this is currently implemented is not correct in general for multiple composed transforms, as you need to unconstrain the outermost value (peel off a transform) before applying the next check
- [x] Much of the code in `Transform_Mir`, `Mir_Utils`, and `Ast_to_Mir` makes assumptions about sizes/dimensions based on the transform associated with the declaration, which still needs to be expanded or rethought
- [x] stan::math functions for constraining need to take a Jacobian template parameter, like those in stan::io::deserializer. This should be an easy change which @SteveBronder has agreed to do
 
-----
## Future work
As a follow on PR, the parser will be updated to parse declarations like
```stan
real <offset=1, multiplier=3, lower=0> variable;
```
As brought up in #659. Further extensions to allow more general compositions are left for others to consider.

-------

#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [x] OR, no user-facing changes were made

## Release notes

Internal refactor to allow composing multiple transforms of a single variable

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by SteveBronder** [comment]
I'm good with 

> The other option is maintain my current approach but just assert that the data block (..etc) cannot have anything other than a primitive (single) transform. That means the debug data generation and constraint check system etc could all remain mostly unchanged, and the only open issue to resolve here would be the dimension issues.

This starts delving into feature creep a bit, but I'd like to think about how user supplied constraints would interact here. I _think_ what we are saying here is all well and good as long as in the future for constraining transformed parameters we do something where the main jist is to just expose the `_constrain` functions. Then in the C++ when we see those we place the `jacobian__` template parameter after the function signature and add the lp parameter. So when a user writes 

```stan
matrix[N, M] X = lb_constrain(X_other);
```

We generate something like 

```cpp
Eigen::Matrix<local_scalar_t__, -1, -1> X = lb_constrain<jacobian__>(X_other, lp);
```

And then I think in `transformed_inits` when we see a `_constrain()` function somewhere a user has added we have to call the associated `_free` function before it's written to the output vector.

**Comment by WardBrian** [comment]
That is how I would imagine it yes. Nothing I'm doing should make that any harder, and if anything might make it a little easier.

The biggest issue from that standpoint I think is for transforms that change the dimensionality (like the matrix constraints we've discussed over email, or `simplex`). Trying to solve in-general what the correct dimensions are is going to be a big headache.

If you want to look at the current output I think I've nested everything as calls correctly, rather than repeated assignments. 

I still need to change the template parameters in the `read` call for special cases, but it's getting much closer now.

**Comment by bob-carpenter** [comment]
In general, a transform consists of several parts:

1. a transform from "constrained" to "unconstrained"
2. the inverse of the transform
3. the log absolute Jacobian determinant function for the inverse transform
4. dimensionality information (e.g. that simplex maps K - 1 unconstrained parameters to a K-vector)

We use (1) for transforming inits and (2)+(3) for transforming parameters in the `log_prob` function, and then just (2) for transforming parameters when writing them out in `write_array`.

There's no reason in principle these can't be chained if the dimensions conform, but if you want to keep track of the ranges beyond the last transform, that's much trickier.

**Comment by WardBrian** [comment]
Currently getting CI failures about template substitution


<details><summary>See Error:</summary>
<p>

```
n file included from /mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun.hpp:240:
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:83:12: error: no matching function for call to 'ordered_constrain'
    return ordered_constrain(x, lp);
           ^~~~~~~~~~~~~~~~~
../../test/integration/good/declarations.hpp:3280:16: note: in instantiation of function template specialization 'stan::math::ordered_constrain<false, std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > >' requested here
      par_g1 = ordered_constrain<jacobian__>(
               ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:81:13: note: candidate template ignored: couldn't infer template argument 'Jacobian'
inline auto ordered_constrain(const T& x, return_type_t<T>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:54:13: note: candidate template ignored: requirement 'is_eigen_col_vector<vector<Matrix<double, -1, 1, 0, -1, 1>, allocator<Matrix<double, -1, 1, 0, -1, 1> > > >::value' was not satisfied [with EigVec = std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >]
inline auto ordered_constrain(const EigVec& x, value_type_t<EigVec>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:26:29: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline plain_type_t<EigVec> ordered_constrain(const EigVec& x) {
                            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:83:12: error: no matching function for call to 'ordered_constrain'
    return ordered_constrain(x, lp);
           ^~~~~~~~~~~~~~~~~
../../test/integration/good/declarations.hpp:3285:16: note: in instantiation of function template specialization 'stan::math::ordered_constrain<false, std::vector<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::allocator<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > > > >' requested here
      par_g2 = ordered_constrain<jacobian__>(
               ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:81:13: note: candidate template ignored: couldn't infer template argument 'Jacobian'
inline auto ordered_constrain(const T& x, return_type_t<T>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:54:13: note: candidate template ignored: requirement 'is_eigen_col_vector<vector<vector<Matrix<double, -1, 1, 0, -1, 1>, allocator<Matrix<double, -1, 1, 0, -1, 1> > >, allocator<vector<Matrix<double, -1, 1, 0, -1, 1>, allocator<Matrix<double, -1, 1, 0, -1, 1> > > > > >::value' was not satisfied [with EigVec = std::vector<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::allocator<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > > >]
inline auto ordered_constrain(const EigVec& x, value_type_t<EigVec>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:26:29: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline plain_type_t<EigVec> ordered_constrain(const EigVec& x) {
                            ^
../../test/integration/good/declarations.hpp:3290:16: error: no matching function for call to 'ordered_constrain'
      par_g3 = ordered_constrain<jacobian__>(
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:81:13: note: candidate template ignored: substitution failure [with Jacobian = false, T = std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >]
inline auto ordered_constrain(const T& x, return_type_t<T>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:54:13: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'EigVec'
inline auto ordered_constrain(const EigVec& x, value_type_t<EigVec>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/fun/ordered_constrain.hpp:73:6: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'VarVec'
auto ordered_constrain(const VarVec& x, scalar_type_t<VarVec>& lp) {
     ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:26:29: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline plain_type_t<EigVec> ordered_constrain(const EigVec& x) {
                            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/fun/ordered_constrain.hpp:25:13: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline auto ordered_constrain(const T& x) {
            ^
../../test/integration/good/declarations.hpp:3295:16: error: no matching function for call to 'ordered_constrain'
      par_g4 = ordered_constrain<jacobian__>(
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:81:13: note: candidate template ignored: substitution failure [with Jacobian = false, T = std::vector<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > >, std::allocator<std::vector<Eigen::Matrix<double, -1, 1, 0, -1, 1>, std::allocator<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > > >]
inline auto ordered_constrain(const T& x, return_type_t<T>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:54:13: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'EigVec'
inline auto ordered_constrain(const EigVec& x, value_type_t<EigVec>& lp) {
            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/fun/ordered_constrain.hpp:73:6: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'VarVec'
auto ordered_constrain(const VarVec& x, scalar_type_t<VarVec>& lp) {
     ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/prim/fun/ordered_constrain.hpp:26:29: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline plain_type_t<EigVec> ordered_constrain(const EigVec& x) {
                            ^
/mnt/nvme1n1/workspace/stanc3_PR-947/performance-tests-cmdstan/cmdstan/stan/lib/stan_math/stan/math/rev/fun/ordered_constrain.hpp:25:13: note: candidate function template not viable: requires single argument 'x', but 2 arguments were provided
inline auto ordered_constrain(const T& x) {
            ^
```

</p></details>

**Comment by WardBrian** [comment]
Okay at least some of them are because I need to figure out how to pass the dimension args to the cholesky constraints. Not sure why `ordered_constrain` is failing though

**Comment by SteveBronder** [comment]
Oh, looking those over we need the `lp` parameter to have it's own template parameter in the math library since sometimes that lp can be a `var` but the matrix can have a scalar double type. So right now the `lp` type is based on the scalar of the input `x`, but that's wrong here in log_prob. I can fix this upstream pretty easily

**Comment by WardBrian** [comment]
I think I have a decent abstraction for FnReadParam for all of the transforms we currently implement, but I'm baking in some pretty strong assumptions by doing so that will have to change if we let users define arbitrary constraints (particularly if they change dimension)

I'm starting to wonder if there is merit toward reintroducing an internal FnConstrain which handles that sort of stuff. I know #872 only just got rid of that.

**Comment by WardBrian** [comment]
Okay, so I think there are 3 main things needed before the compiler work here is done.

- [ ] The transform_mismatch warning in Pedantic mode - I'm not sure exactly what the correct thing to do here is, may need to rethink the warning entirely. 
https://github.com/WardBrian/stanc3/blob/8ec5be337af9caa9019d4e0209d7880e8f6c30ed/src/analysis_and_optimization/Pedantic_dist_warnings.ml#L79-L98

- [ ] Related, `trans_bounds_values` in Mir_utils may not be well-defined in chain cases: 
https://github.com/WardBrian/stanc3/blob/8ec5be337af9caa9019d4e0209d7880e8f6c30ed/src/analysis_and_optimization/Mir_utils.ml#L44-L63

- [ ] Finally, we need all of the free/constrain functions to be vectorized. @SteveBronder is on that.

Once these are done we can start worrying about how to actually instantiate this/the language design for it. I think I'll want at least one working version before this gets merged so we can test some things, even if it ends up in a separate PR.

**Comment by WardBrian** [comment]
I just wanted to ping @rybern on this -- this is the WIP PR for composable transforms that touches a lot of that codegen. We should chat about how that could affect the tuples PR

**Comment by WardBrian** [comment]
I think we've decided #971 supersedes this PR.

**Pull request closed without merging**
