### PR TITLE
Fix tests for optimizations

### PR DESCRIPTION
**Pull request by rok-cesnovar**
#### Submission Checklist

- [ ] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [ ] OR, no user-facing changes were made

@WardBrian can we add a "simple" optimization bug to stress test this? Something that will produce the wrong results.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
I've introduced a bug which swaps the order of arguments to `fma` in the partial evaluator. If it still passes tests that is probably because none of the tests we're running feature a float multiply add. We next need to address https://github.com/stan-dev/performance-tests-cmdstan/issues/38, e.g. we need more tests in this set that get optimized.

**Comment by rok-cesnovar** [comment]
> We next need to address https://github.com/stan-dev/performance-tests-cmdstan/issues/38, e.g. we need more tests in this set that get optimized.

Agreed. Where do we want to put these? In the perf-cmdstan repo or stanc3?

We can then do the same for https://github.com/stan-dev/performance-tests-cmdstan/issues/30

**Comment by WardBrian** [comment]
It may be arbitrary, but to me I think anything which is testing that the model compiles (e.g., what you're proposing in https://github.com/stan-dev/performance-tests-cmdstan/issues/30) can live here in stanc3, but anything which we want to actually run should be in performance-tests-cmdstan. Sound reasonable?

**Comment by rok-cesnovar** [comment]
Yeah, good call.

**Comment by WardBrian** [comment]
We already have https://github.com/stan-dev/stanc3/tree/master/test/integration/downstream, which is a good place to potentially put more of those models we want to make sure compile. I don't believe we're currently compiling that folder all the way down to a binary

**Review by WardBrian — APPROVED** [review]

**Pull request merged**
