### PR TITLE
Add 3 to version number

### LINKED ISSUE #443: Fix stanc --version
I think stanc --version should state that this is stanc3

The old parser returns "stanc vesion 2.22.0" and stanc3 returns "stanc v2.22.0 (Unix)". 

Can we change this so that stanc3 returns "stanc3 v2.22.0 (Unix)".

### PR DESCRIPTION
**Pull request by seantalts**
Fixes #443

### CODE REVIEW

**Comment by rok-cesnovar** [comment]
As we already know that there will be a cmdstan 2.22.1, do you think it makes sense to also make a 2.22.1 stanc3 with this fix?

**Comment by seantalts** [comment]
Sure, all anyone has to do to release a new stanc3 is make an annotated git tag (`git tag -a`. Jenkins will create and upload the release automatically. Not sure what information to put in the git annotations, though, haha. Ideas?

**Comment by rok-cesnovar** [comment]
You mean what the tag should be? :) Well the last annotation was  v2.22.0. So v2.22.1 i guess :/ Its confusing but idk.

**Comment by seantalts** [comment]
Agreed the tag should be v2.22.1, I think. But there is also an annotation that must go with it. 

image

**Comment by rok-cesnovar** [comment]
"Fix version output to distinguish between stanc and stanc3" That sound good?

**Pull request merged**
