### PR TITLE
[WIP] [CI] Build binaries in parallel

### PR DESCRIPTION
**Pull request by serban-nicusor-toptal**
#### Submission Checklist

- [ ] Run unit tests
- Documentation
    - [ ] If a user-facing facing change was made, the documentation PR is here: <LINK>
    - [ ] OR, no user-facing changes were made

## Release notes

Build binaries in parallel on Jenkins.

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by WardBrian** [comment]
Do we have some way of testing this before merging to master?

**Comment by serban-nicusor-toptal** [comment]
Yes, I ran a replay job here: https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/PR-1244/3/pipeline
Forcing it to build the binaries

**Comment by WardBrian** [comment]
Ready to review/merge?

**Comment by serban-nicusor-toptal** [comment]
Hey @WardBrian I think it is. We ran the builds, tests, and tests at O=1. I hope we covered all scenarios. Thank you.

**Review by WardBrian — APPROVED** [review]
Thanks @serban-nicusor-toptal !

**Pull request merged**
