### PR TITLE
[Fix] Properly demote to AoS for variable in for loop when body is an inlined function

### PR DESCRIPTION
**Pull request by WardBrian**
#### Submission Checklist

- [x] Run unit tests
- Documentation
    - [x] OR, no user-facing changes were made

## Release notes

Fix a bug in the memory pattern optimization where a for loop generated for the function inliner would prevent detection of for loops higher in the control flow graph. 

Initially reported by @hsbadr  for the rstanarm `polr` model on the forums [here](https://discourse.mc-stan.org/t/status-on-rstan-cran-and-latest-versions-of-stan/28293/15?u=wardbrian)

## Copyright and Licensing

By submitting this pull request, the copyright holder is agreeing to 
license the submitted work under the BSD 3-clause license (https://opensource.org/licenses/BSD-3-Clause)

### CODE REVIEW

**Comment by hsbadr** [comment]
@WardBrian Another one with `EpiNow2` R packages when optimizations are enabled:
```c++
stanExports_estimate_infections.h(4545): error: identifier "inline_update_Rt_R_sym460__" is undefined
                                            inline_update_Rt_R_sym460__);
                                            ^
```

**Comment by WardBrian** [comment]
@hsbadr can you point me toward the Stan code for that model?

**Comment by hsbadr** [comment]
https://github.com/epiforecasts/EpiNow2/tree/master/inst/stan

**Comment by SteveBronder** [comment]
@hsbadr did that error happen before this PR?

**Comment by hsbadr** [comment]
> did that error happen before this PR?

I didn't try to build `EpiNow2` with `stanc3` `O1` optimizations before this PR. Should I test it?

**Comment by hsbadr** [comment]
@SteveBronder It fails with and without this PR if `O1` optimizations are enabled. Otherwise, it compiles successfully. So, it's an issue with `stanc3` optimizations, not related to this PR.

**Comment by WardBrian** [comment]
@SteveBronder it's an issue with if the name of the argument before inlining is the same as a variable later in the function.

MRE:

```stan
functions {
  vector foo(vector oR) {
    int ot = num_elements(oR);
    
    vector[ot] R = oR;
    
    return (R);
  }
}
data {
  int N;
}
transformed parameters {
  vector[N] R;
  vector[N] out;
  out = foo(R);
}

```

**Comment by WardBrian** [comment]
This generates code like

```
 data vector[0] inline_foo_return_sym1__;
  {
    int inline_foo_ot_sym2__;
    inline_foo_ot_sym2__ = num_elements(inline_foo_R_sym3__);
    FnValidateSize__("R", "ot", inline_foo_ot_sym2__);
    vector[inline_foo_ot_sym2__] inline_foo_R_sym3__;
    inline_foo_R_sym3__ = inline_foo_R_sym3__;
    inline_foo_return_sym1__ = inline_foo_R_sym3__;
  }
  out = inline_foo_return_sym1__;
````

but it should generate code like

```
data vector[0] inline_foo_return_sym1__;
  {
    int inline_foo_ot_sym2__;
    inline_foo_ot_sym2__ = num_elements(R_renamed);
    FnValidateSize__("R", "ot", inline_foo_ot_sym2__);
    vector[inline_foo_ot_sym2__] inline_foo_R_sym3__;
  }
  out = R_renamed;
```

**Pull request merged**
